#!/usr/bin/env node
// research-index.mjs — regenerate docs/research/INDEX.md from each doc's YAML
// frontmatter. Zero-dep, idempotent. SSOT = the docs' frontmatter (AGENTS.md rule #3).
//
//   node research-index.mjs <researchDir>            # write/refresh INDEX.md
//   node research-index.mjs <researchDir> --check     # exit 1 if INDEX.md is stale
//
// Importable: `import { regenerate } from "./research-index.mjs"` (used by the
// format-edited write hook to keep the index synced automatically).
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const BEGIN = '<!-- BEGIN:auto (generated by research-index.mjs — do not edit by hand) -->';
const END = '<!-- END:auto -->';
const cell = (s) => (s || '').replace(/\r?\n/g, ' ').replace(/\|/g, '/').trim();

function fm(txt) {
  const m = txt.match(/^---\s*([\s\S]*?)\n---/);
  const b = m ? m[1] : '';
  const g = (k) => {
    const line = b.split('\n').find((l) => l.startsWith(k + ':'));
    return (line ? line.slice(k.length + 1) : '').trim().replace(/^["']|["']$/g, '');
  };
  return {
    type: g('type'),
    slug: g('slug'),
    domain: g('domain'),
    status: g('status'),
    updated: g('updated'),
    tags: g('tags'),
    abstract: g('abstract').replace(/^>\s*/, ''),
  };
}

export function scan(dir) {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md') && f !== 'INDEX.md')
    .map((f) => ({ file: f, ...fm(readFileSync(join(dir, f), 'utf8')) }))
    .filter((d) => d.slug);
}

// Files that declare the same frontmatter `slug` — an accidental duplicate that would
// otherwise yield two index rows for one logical doc (or silently overwrite work).
export function duplicateSlugs(dir) {
  const bySlug = new Map();
  for (const d of scan(dir)) {
    const list = bySlug.get(d.slug) ?? [];
    list.push(d.file);
    bySlug.set(d.slug, list);
  }
  return [...bySlug]
    .filter(([, files]) => files.length > 1)
    .map(([slug, files]) => ({ slug, files }));
}

export function buildAuto(dir) {
  const rows = scan(dir).sort((a, b) => (b.updated || '').localeCompare(a.updated || ''));
  const head = '| type | slug | domain | status | updated | tags | abstract |\n|---|---|---|---|---|---|---|';
  const body =
    rows
      .map(
        (d) =>
          `| ${cell(d.type)} | ${cell(d.slug)} | ${cell(d.domain)} | ${cell(d.status)} | ${cell(d.updated)} | ${cell(d.tags)} | ${cell(d.abstract).slice(0, 120)} |`,
      )
      .join('\n') || '| _(none yet)_ |  |  |  |  |  |  |';
  return `${BEGIN}\n${head}\n${body}\n${END}`;
}

function splice(cur, auto) {
  const i = cur.indexOf(BEGIN);
  const j = cur.indexOf(END);
  if (i === -1 || j === -1) return null;
  return cur.slice(0, i) + auto + cur.slice(j + END.length);
}

export function regenerate(dir, { check = false } = {}) {
  const idx = join(dir, 'INDEX.md');
  const auto = buildAuto(dir);
  const cur = existsSync(idx) ? readFileSync(idx, 'utf8') : '';
  const spliced = splice(cur, auto);
  const next =
    spliced != null
      ? spliced
      : `# Research library\n\n> Generated manifest. Prose outside the auto block is preserved.\n\n${auto}\n`;
  if (check) return cur.trim() === next.trim();
  if (cur !== next) writeFileSync(idx, next);
  return true;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const dir = process.argv[2];
  const check = process.argv.includes('--check');
  if (!dir || !existsSync(dir)) {
    console.error('usage: research-index <researchDir> [--check]');
    process.exit(2);
  }
  const dups = duplicateSlugs(dir);
  const ok = regenerate(dir, { check });
  if (dups.length) {
    for (const d of dups) console.error(`DUPLICATE slug '${d.slug}': ${d.files.join(', ')}`);
    process.exit(1);
  }
  if (check && !ok) {
    console.error(`STALE: ${join(dir, 'INDEX.md')} — run: just research-index ${dir}`);
    process.exit(1);
  }
  console.log(check ? 'in sync' : 'regenerated');
}
