// dialogueContent.contract.test.ts — the client dialogue mirror vs the shipped RON
// (debloat Phase 2: EV-dialogue-client-integrity#ron-bundle-crossref).
//
// `advance_dialogue(choice_idx)` is index-based, so a DIALOGUE_TREES mirror that
// drifts from game-core/content/dialogue_trees/*.ron makes the player pick a
// different server choice than the one shown. The server-module test
// `dialogue_trees_contract_matches_the_shipped_ron` (content_tests.rs) renders the
// SHIPPED trees through the game-core loader into evals/baselines/dialogue-trees.txt;
// this test renders the RUNTIME DIALOGUE_TREES value with the same canonical rules
// and requires byte equality. Neither side parses the other's source.
//
// Canonical form (mirror of render_dialogue_contract): trees sorted by id, nodes
// sorted by id, choices in authored order; `\` and newlines escaped as `\\`/`\n`;
// a missing next node is `-`.
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { type ClientDialogueTree, DIALOGUE_TREES } from './dialogueContent';

const CONTRACT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../evals/baselines/dialogue-trees.txt',
);

const esc = (s: string): string => s.replaceAll('\\', '\\\\').replaceAll('\n', '\\n');
const byId = <T>(entries: Iterable<[string, T]>): [string, T][] =>
  [...entries].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

function renderDialogueContract(trees: ReadonlyMap<string, ClientDialogueTree>): string {
  let out = '';
  for (const [treeId, tree] of byId(trees)) {
    out += `tree ${esc(treeId)}\n`;
    for (const [nodeId, node] of byId(tree.nodes)) {
      out += `node ${esc(nodeId)}\n`;
      out += `text ${esc(node.text)}\n`;
      for (const choice of node.choices) {
        out += `choice ${choice.nextNodeId === null ? '-' : esc(choice.nextNodeId)} ${esc(choice.text)}\n`;
      }
    }
  }
  return out;
}

describe('DIALOGUE_TREES matches the shipped dialogue RON (contract artifact)', () => {
  it('renders byte-equal to evals/baselines/dialogue-trees.txt', () => {
    const committed = readFileSync(CONTRACT, 'utf8');
    expect(committed.length, 'the contract artifact must not be empty').toBeGreaterThan(0);
    expect(
      renderDialogueContract(DIALOGUE_TREES),
      'client/src/ui/dialogueContent.ts drifted from the shipped dialogue RON — bring it in ' +
        'line with evals/baselines/dialogue-trees.txt (regenerated by the server-module ' +
        'dialogue_trees_contract test)',
    ).toBe(committed);
  });

  it('the renderer mirrors the server rules: escaping, ordering, the missing-next dash', () => {
    // Same fixture as content_tests.rs dialogue_trees_contract_renderer_escapes_and_orders.
    const trees: ReadonlyMap<string, ClientDialogueTree> = new Map([
      [
        'b',
        {
          nodes: new Map([
            [
              'z',
              {
                text: 'line1\nchoice x forged',
                choices: [{ text: 'go', nextNodeId: 'a' }],
              },
            ],
            [
              'a',
              {
                text: 'back\\slash',
                choices: [
                  { text: 'second', nextNodeId: null },
                  { text: 'first', nextNodeId: null },
                ],
              },
            ],
          ]),
        },
      ],
      ['a', { nodes: new Map([['n', { text: 'hi', choices: [] }]]) }],
    ]);
    expect(renderDialogueContract(trees)).toBe(
      'tree a\nnode n\ntext hi\n' +
        'tree b\nnode a\ntext back\\\\slash\nchoice - second\nchoice - first\n' +
        'node z\ntext line1\\nchoice x forged\nchoice a go\n',
    );
  });
});
