// ui/screens/helpScreen.ts — Help as a pure screen over the nav kit (ctl-14, CTL14.1; design §9).
// No DOM, SDK, module state or clock. Help's content is generated by `helpModel.ts` and bound into
// `helpView.ts` when it opens; this screen only says which tab shows. The rows are display-only, so
// each tab is one item (`rows`, the panel): LB/RB switch the tab, and A and the D-pad act on nothing.
import { HELP_TABS } from '../helpModel';
import { list, type NavLayout, type NavState, navInit, navStep, tabs } from '../nav';
import type { ButtonStep, ScreenAdapter, ScreenResult } from './types';

export interface HelpState {
  readonly nav: NavState;
}

export interface HelpPaint {
  readonly layout: NavLayout;
  readonly nav: NavState;
}

export interface HelpScreenView {
  paint(p: HelpPaint): void;
}

export const HELP_LAYOUT: NavLayout = tabs(
  HELP_TABS.map((key) => ({ key, layout: list([{ key: 'rows', enabled: true }]) })),
);

export const helpScreen: ScreenAdapter<null, HelpState, HelpScreenView> = {
  nav: true,

  viewModel: () => null,

  init: () => ({ nav: navInit(HELP_LAYOUT) }),

  onButton(_vm, state, btn): ButtonStep<HelpState> {
    const done = (result: ScreenResult, next: HelpState = state) => ({ state: next, result });
    switch (btn.button) {
      case 'B':
        return done(btn.repeat ? 'consumed' : { kind: 'pop' });
      case 'Start':
        return done(btn.repeat ? 'consumed' : { kind: 'popToBase' });
      case 'Select':
        return done(btn.repeat ? 'consumed' : { kind: 'toggleHelp' });
      case 'X':
      case 'Y':
        return done('unhandled');
      case 'LB':
      case 'RB': {
        const nav = navStep(HELP_LAYOUT, state.nav, btn).state;
        return done('consumed', nav === state.nav ? state : { nav });
      }
      default:
        // A and the D-pad: the one item per tab has nothing to move to or act on.
        return done('consumed');
    }
  },

  paint(view, _vm, state): void {
    view.paint({ layout: HELP_LAYOUT, nav: state.nav });
  },
};
