// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HeartbeatReducer from "../heartbeat_reducer";
import JoinReducer from "../join_reducer";
import SyncContentReducer from "../sync_content_reducer";

export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type SyncContentParams = __Infer<typeof SyncContentReducer>;

