// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptChallengeReducer from "../accept_challenge_reducer";
import AdvanceDialogueReducer from "../advance_dialogue_reducer";
import AttemptRecruitReducer from "../attempt_recruit_reducer";
import BuyReducer from "../buy_reducer";
import CancelAccountDeletionReducer from "../cancel_account_deletion_reducer";
import CancelChallengeReducer from "../cancel_challenge_reducer";
import CancelTradeReducer from "../cancel_trade_reducer";
import CareReducer from "../care_reducer";
import ChallengePvpReducer from "../challenge_pvp_reducer";
import ClearQueueReducer from "../clear_queue_reducer";
import CompleteGuestClaimReducer from "../complete_guest_claim_reducer";
import ConfirmTradeReducer from "../confirm_trade_reducer";
import ConsumeCrystalizedEssenceReducer from "../consume_crystalized_essence_reducer";
import DeclineChallengeReducer from "../decline_challenge_reducer";
import DeleteAccountReducer from "../delete_account_reducer";
import DismissDialogueReducer from "../dismiss_dialogue_reducer";
import EnqueueMoveReducer from "../enqueue_move_reducer";
import EssenceTrainReducer from "../essence_train_reducer";
import EvolveReducer from "../evolve_reducer";
import FleeReducer from "../flee_reducer";
import HealPartyReducer from "../heal_party_reducer";
import JoinGameReducer from "../join_game_reducer";
import ProposeTradeReducer from "../propose_trade_reducer";
import RespondTradeReducer from "../respond_trade_reducer";
import SellReducer from "../sell_reducer";
import SetMoveReducer from "../set_move_reducer";
import SetNicknameReducer from "../set_nickname_reducer";
import SetPartySlotReducer from "../set_party_slot_reducer";
import SetProfileNameReducer from "../set_profile_name_reducer";
import StartBattleReducer from "../start_battle_reducer";
import StartGuestClaimReducer from "../start_guest_claim_reducer";
import SubmitAttackReducer from "../submit_attack_reducer";
import SubmitPvpActionReducer from "../submit_pvp_action_reducer";
import SwapActiveReducer from "../swap_active_reducer";
import SyncContentReducer from "../sync_content_reducer";
import TalkReducer from "../talk_reducer";
import TrainReducer from "../train_reducer";
import UseBattleItemReducer from "../use_battle_item_reducer";

export type AcceptChallengeParams = __Infer<typeof AcceptChallengeReducer>;
export type AdvanceDialogueParams = __Infer<typeof AdvanceDialogueReducer>;
export type AttemptRecruitParams = __Infer<typeof AttemptRecruitReducer>;
export type BuyParams = __Infer<typeof BuyReducer>;
export type CancelAccountDeletionParams = __Infer<typeof CancelAccountDeletionReducer>;
export type CancelChallengeParams = __Infer<typeof CancelChallengeReducer>;
export type CancelTradeParams = __Infer<typeof CancelTradeReducer>;
export type CareParams = __Infer<typeof CareReducer>;
export type ChallengePvpParams = __Infer<typeof ChallengePvpReducer>;
export type ClearQueueParams = __Infer<typeof ClearQueueReducer>;
export type CompleteGuestClaimParams = __Infer<typeof CompleteGuestClaimReducer>;
export type ConfirmTradeParams = __Infer<typeof ConfirmTradeReducer>;
export type ConsumeCrystalizedEssenceParams = __Infer<typeof ConsumeCrystalizedEssenceReducer>;
export type DeclineChallengeParams = __Infer<typeof DeclineChallengeReducer>;
export type DeleteAccountParams = __Infer<typeof DeleteAccountReducer>;
export type DismissDialogueParams = __Infer<typeof DismissDialogueReducer>;
export type EnqueueMoveParams = __Infer<typeof EnqueueMoveReducer>;
export type EssenceTrainParams = __Infer<typeof EssenceTrainReducer>;
export type EvolveParams = __Infer<typeof EvolveReducer>;
export type FleeParams = __Infer<typeof FleeReducer>;
export type HealPartyParams = __Infer<typeof HealPartyReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type ProposeTradeParams = __Infer<typeof ProposeTradeReducer>;
export type RespondTradeParams = __Infer<typeof RespondTradeReducer>;
export type SellParams = __Infer<typeof SellReducer>;
export type SetMoveParams = __Infer<typeof SetMoveReducer>;
export type SetNicknameParams = __Infer<typeof SetNicknameReducer>;
export type SetPartySlotParams = __Infer<typeof SetPartySlotReducer>;
export type SetProfileNameParams = __Infer<typeof SetProfileNameReducer>;
export type StartBattleParams = __Infer<typeof StartBattleReducer>;
export type StartGuestClaimParams = __Infer<typeof StartGuestClaimReducer>;
export type SubmitAttackParams = __Infer<typeof SubmitAttackReducer>;
export type SubmitPvpActionParams = __Infer<typeof SubmitPvpActionReducer>;
export type SwapActiveParams = __Infer<typeof SwapActiveReducer>;
export type SyncContentParams = __Infer<typeof SyncContentReducer>;
export type TalkParams = __Infer<typeof TalkReducer>;
export type TrainParams = __Infer<typeof TrainReducer>;
export type UseBattleItemParams = __Infer<typeof UseBattleItemReducer>;

