//! Build script (M8.9e): embed the glob-loaded content registries.
//!
//! Each registry is a DIRECTORY of `*.ron` files under `content/<reg>/`. We read
//! the directory, keep only `*.ron` files, sort them by filename (byte order, so
//! the embed is deterministic and OS-readdir-order-independent), and emit a Rust
//! static `<REG>_RON_PARTS: &[(&str, &str)]` whose entries are
//! `(filename, include_str!(absolute_path))` in sorted order.
//!
//! `include_str!` in the generated file (which lives in `$OUT_DIR`) resolves
//! relative to that file, NOT the crate root, so the embedded paths MUST be
//! absolute (built from `CARGO_MANIFEST_DIR`).
//!
//! `type_chart` is NOT migrated (still a single `include_str!` in content.rs).
//!
//! ZERO new dependencies — std only.

use std::fmt::Write as _;
use std::path::Path;

/// The five glob-loaded registries, each a directory of `*.ron` parts.
const REGISTRIES: &[&str] = &["zones", "species", "skills", "items", "encounters"];

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by cargo");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");

    // Re-run if the top-level content dir changes (new/removed registry dirs).
    println!("cargo:rerun-if-changed=content");

    let mut generated = String::new();
    generated.push_str(
        "// @generated by build.rs (M8.9e) — do not edit. Sorted-filename content parts.\n",
    );

    for reg in REGISTRIES {
        let dir = Path::new(&manifest_dir).join("content").join(reg);
        if !dir.is_dir() {
            // Hard build error: never silently emit an empty list (the
            // sorted-static test asserts non-empty, and a missing registry
            // directory is a real content/build mistake we want surfaced loudly).
            panic!(
                "M8.9e build.rs: content registry directory missing: {}",
                dir.display()
            );
        }

        // Re-run if a file is added to / removed from this registry directory.
        println!("cargo:rerun-if-changed=content/{reg}");

        let mut parts: Vec<(String, String)> = Vec::new();
        let entries = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("M8.9e build.rs: cannot read {}: {e}", dir.display()));
        for entry in entries {
            let entry =
                entry.unwrap_or_else(|e| panic!("M8.9e build.rs: bad dir entry in {reg}: {e}"));
            let path = entry.path();
            // Keep only regular files whose extension is exactly "ron".
            if path.extension().and_then(|e| e.to_str()) != Some("ron") {
                continue;
            }
            if !path.is_file() {
                continue;
            }
            let file_name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or_else(|| panic!("M8.9e build.rs: non-UTF8 filename in {reg}"))
                .to_string();
            let abs = path
                .to_str()
                .unwrap_or_else(|| panic!("M8.9e build.rs: non-UTF8 path in {reg}"))
                .to_string();
            parts.push((file_name, abs));
        }

        if parts.is_empty() {
            panic!(
                "M8.9e build.rs: content registry {} has no *.ron files",
                dir.display()
            );
        }

        // Deterministic embed: sort by filename in byte order.
        parts.sort_by(|a, b| a.0.cmp(&b.0));

        // Re-run if any embedded file changes.
        for (_, abs) in &parts {
            println!("cargo:rerun-if-changed={abs}");
        }

        let const_name = format!("{}_RON_PARTS", reg.to_uppercase());
        writeln!(
            generated,
            "pub(crate) const {const_name}: &[(&str, &str)] = &["
        )
        .unwrap();
        for (file_name, abs) in &parts {
            // file_name and abs come from the crate's own content tree (trusted),
            // and RON filenames are simple; escape defensively all the same.
            writeln!(generated, "    ({:?}, include_str!({:?})),", file_name, abs).unwrap();
        }
        generated.push_str("];\n");
    }

    let out_path = Path::new(&out_dir).join("content_parts.rs");
    std::fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("M8.9e build.rs: cannot write {}: {e}", out_path.display()));
}
