// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ChallengeStatus,
} from "./types";


export default __t.row({
  challengeId: __t.u64().primaryKey().name("challenge_id"),
  challenger: __t.identity(),
  target: __t.identity(),
  challengerPartyIds: __t.array(__t.u64()).name("challenger_party_ids"),
  get status() {
    return ChallengeStatus;
  },
  createdAtMs: __t.i64().name("created_at_ms"),
});
