// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BattleState,
} from "./types";


export default __t.row({
  battleId: __t.u64().primaryKey().name("battle_id"),
  playerIdentity: __t.identity().name("player_identity"),
  opponentIdentity: __t.identity().name("opponent_identity"),
  get state() {
    return BattleState;
  },
  partyMonsterIds: __t.array(__t.u64()).name("party_monster_ids"),
  opponentMonsterIds: __t.array(__t.u64()).name("opponent_monster_ids"),
  createdAtMs: __t.i64().name("created_at_ms"),
});
