// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EssenceRequirementRow,
  TrustTier,
} from "./types";


export default __t.row({
  pathId: __t.u64().primaryKey().name("path_id"),
  edgeId: __t.u32().name("edge_id"),
  fromSpecies: __t.u32().name("from_species"),
  toSpecies: __t.u32().name("to_species"),
  minLevel: __t.u8().name("min_level"),
  get essence() {
    return __t.array(EssenceRequirementRow);
  },
  get minTrustTier() {
    return __t.option(TrustTier).name("min_trust_tier");
  },
  minQualityTimeTier: __t.option(__t.u8()).name("min_quality_time_tier"),
  minNutritionPct: __t.option(__t.u8()).name("min_nutrition_pct"),
});
