// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fusionId: __t.u64().primaryKey().name("fusion_id"),
  aSpecies: __t.u32().name("a_species"),
  bSpecies: __t.u32().name("b_species"),
  toSpecies: __t.u32().name("to_species"),
});
