// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  locationId: __t.u32().primaryKey().name("location_id"),
  zoneId: __t.u32().name("zone_id"),
  tileX: __t.i32().name("tile_x"),
  tileY: __t.i32().name("tile_y"),
  costItemId: __t.option(__t.u32()).name("cost_item_id"),
  costQty: __t.u32().name("cost_qty"),
  cooldownMs: __t.i64().name("cooldown_ms"),
});
