// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptChallengeReducer from "./accept_challenge_reducer";
import AdvanceDialogueReducer from "./advance_dialogue_reducer";
import AttemptRecruitReducer from "./attempt_recruit_reducer";
import BuyReducer from "./buy_reducer";
import CancelChallengeReducer from "./cancel_challenge_reducer";
import CancelTradeReducer from "./cancel_trade_reducer";
import CareReducer from "./care_reducer";
import ChallengePvpReducer from "./challenge_pvp_reducer";
import ClearQueueReducer from "./clear_queue_reducer";
import ConfirmTradeReducer from "./confirm_trade_reducer";
import DeclineChallengeReducer from "./decline_challenge_reducer";
import DismissDialogueReducer from "./dismiss_dialogue_reducer";
import EnqueueMoveReducer from "./enqueue_move_reducer";
import EvolveReducer from "./evolve_reducer";
import FleeReducer from "./flee_reducer";
import FuseReducer from "./fuse_reducer";
import HealPartyReducer from "./heal_party_reducer";
import JoinGameReducer from "./join_game_reducer";
import ProposeTradeReducer from "./propose_trade_reducer";
import RespondTradeReducer from "./respond_trade_reducer";
import SellReducer from "./sell_reducer";
import SetMoveReducer from "./set_move_reducer";
import SetNicknameReducer from "./set_nickname_reducer";
import SetPartySlotReducer from "./set_party_slot_reducer";
import SetProfileNameReducer from "./set_profile_name_reducer";
import StartBattleReducer from "./start_battle_reducer";
import SubmitAttackReducer from "./submit_attack_reducer";
import SubmitPvpActionReducer from "./submit_pvp_action_reducer";
import SwapActiveReducer from "./swap_active_reducer";
import SyncContentReducer from "./sync_content_reducer";
import TalkReducer from "./talk_reducer";
import TrainReducer from "./train_reducer";
import UseBattleItemReducer from "./use_battle_item_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BattleRow from "./battle_table";
import BattleChallengeRow from "./battle_challenge_table";
import CharacterRow from "./character_table";
import ConfigRow from "./config_table";
import FusionRow from "./fusion_table";
import HealLocationRowRow from "./heal_location_row_table";
import InventoryRow from "./inventory_table";
import ItemRowRow from "./item_row_table";
import MonsterPubRow from "./monster_pub_table";
import MyConversationRow from "./my_conversation_table";
import NpcRow from "./npc_table";
import PlayerRow from "./player_table";
import PlayerQuestRow from "./player_quest_table";
import ProfileRow from "./profile_table";
import ShopItemRowRow from "./shop_item_row_table";
import ShopRowRow from "./shop_row_table";
import SkillRowRow from "./skill_row_table";
import SpeciesRowRow from "./species_row_table";
import TradeOfferRow from "./trade_offer_table";
import TypeRelationRowRow from "./type_relation_row_table";
import ZoneDefRow from "./zone_def_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  battle: __table({
    name: 'battle',
    indexes: [
      { accessor: 'battle_id', name: 'battle_battle_id_idx_btree', algorithm: 'btree', columns: [
        'battleId',
      ] },
      { accessor: 'opponent_identity', name: 'battle_opponent_identity_idx_btree', algorithm: 'btree', columns: [
        'opponentIdentity',
      ] },
      { accessor: 'player_identity', name: 'battle_player_identity_idx_btree', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'battle_battle_id_key', constraint: 'unique', columns: ['battleId'] },
    ],
  }, BattleRow),
  battle_challenge: __table({
    name: 'battle_challenge',
    indexes: [
      { accessor: 'challenge_id', name: 'battle_challenge_challenge_id_idx_btree', algorithm: 'btree', columns: [
        'challengeId',
      ] },
      { accessor: 'challenger', name: 'battle_challenge_challenger_idx_btree', algorithm: 'btree', columns: [
        'challenger',
      ] },
      { accessor: 'target', name: 'battle_challenge_target_idx_btree', algorithm: 'btree', columns: [
        'target',
      ] },
    ],
    constraints: [
      { name: 'battle_challenge_challenge_id_key', constraint: 'unique', columns: ['challengeId'] },
    ],
  }, BattleChallengeRow),
  character: __table({
    name: 'character',
    indexes: [
      { accessor: 'entity_id', name: 'character_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'zone_id', name: 'character_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'character_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CharacterRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'id', name: 'config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConfigRow),
  fusion: __table({
    name: 'fusion',
    indexes: [
      { accessor: 'fusion_id', name: 'fusion_fusion_id_idx_btree', algorithm: 'btree', columns: [
        'fusionId',
      ] },
    ],
    constraints: [
      { name: 'fusion_fusion_id_key', constraint: 'unique', columns: ['fusionId'] },
    ],
  }, FusionRow),
  heal_location_row: __table({
    name: 'heal_location_row',
    indexes: [
      { accessor: 'location_id', name: 'heal_location_row_location_id_idx_btree', algorithm: 'btree', columns: [
        'locationId',
      ] },
      { accessor: 'zone_id', name: 'heal_location_row_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'heal_location_row_location_id_key', constraint: 'unique', columns: ['locationId'] },
    ],
  }, HealLocationRowRow),
  inventory: __table({
    name: 'inventory',
    indexes: [
      { accessor: 'inv_id', name: 'inventory_inv_id_idx_btree', algorithm: 'btree', columns: [
        'invId',
      ] },
      { accessor: 'owner_identity', name: 'inventory_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
    ],
    constraints: [
      { name: 'inventory_inv_id_key', constraint: 'unique', columns: ['invId'] },
    ],
  }, InventoryRow),
  item_row: __table({
    name: 'item_row',
    indexes: [
      { accessor: 'id', name: 'item_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'item_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemRowRow),
  monster_pub: __table({
    name: 'monster_pub',
    indexes: [
      { accessor: 'monster_id', name: 'monster_pub_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
      { accessor: 'owner_identity', name: 'monster_pub_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
    ],
    constraints: [
      { name: 'monster_pub_monster_id_key', constraint: 'unique', columns: ['monsterId'] },
    ],
  }, MonsterPubRow),
  npc: __table({
    name: 'npc',
    indexes: [
      { accessor: 'entity_id', name: 'npc_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'npc_id', name: 'npc_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { accessor: 'zone_id', name: 'npc_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'npc_entity_id_key', constraint: 'unique', columns: ['entityId'] },
      { name: 'npc_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'entity_id', name: 'player_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  player_quest: __table({
    name: 'player_quest',
    indexes: [
      { accessor: 'owner_identity', name: 'player_quest_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
      { accessor: 'pq_id', name: 'player_quest_pq_id_idx_btree', algorithm: 'btree', columns: [
        'pqId',
      ] },
    ],
    constraints: [
      { name: 'player_quest_pq_id_key', constraint: 'unique', columns: ['pqId'] },
    ],
  }, PlayerQuestRow),
  profile: __table({
    name: 'profile',
    indexes: [
      { accessor: 'identity', name: 'profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ProfileRow),
  shop_item_row: __table({
    name: 'shop_item_row',
    indexes: [
      { accessor: 'shop_id', name: 'shop_item_row_shop_id_idx_btree', algorithm: 'btree', columns: [
        'shopId',
      ] },
      { accessor: 'shop_item_id', name: 'shop_item_row_shop_item_id_idx_btree', algorithm: 'btree', columns: [
        'shopItemId',
      ] },
    ],
    constraints: [
      { name: 'shop_item_row_shop_item_id_key', constraint: 'unique', columns: ['shopItemId'] },
    ],
  }, ShopItemRowRow),
  shop_row: __table({
    name: 'shop_row',
    indexes: [
      { accessor: 'shop_id', name: 'shop_row_shop_id_idx_btree', algorithm: 'btree', columns: [
        'shopId',
      ] },
    ],
    constraints: [
      { name: 'shop_row_shop_id_key', constraint: 'unique', columns: ['shopId'] },
    ],
  }, ShopRowRow),
  skill_row: __table({
    name: 'skill_row',
    indexes: [
      { accessor: 'id', name: 'skill_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'skill_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SkillRowRow),
  species_row: __table({
    name: 'species_row',
    indexes: [
      { accessor: 'id', name: 'species_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'species_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpeciesRowRow),
  trade_offer: __table({
    name: 'trade_offer',
    indexes: [
      { accessor: 'counterparty', name: 'trade_offer_counterparty_idx_btree', algorithm: 'btree', columns: [
        'counterparty',
      ] },
      { accessor: 'initiator', name: 'trade_offer_initiator_idx_btree', algorithm: 'btree', columns: [
        'initiator',
      ] },
      { accessor: 'trade_id', name: 'trade_offer_trade_id_idx_btree', algorithm: 'btree', columns: [
        'tradeId',
      ] },
    ],
    constraints: [
      { name: 'trade_offer_trade_id_key', constraint: 'unique', columns: ['tradeId'] },
    ],
  }, TradeOfferRow),
  type_relation_row: __table({
    name: 'type_relation_row',
    indexes: [
      { accessor: 'id', name: 'type_relation_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'type_relation_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TypeRelationRowRow),
  zone_def: __table({
    name: 'zone_def',
    indexes: [
      { accessor: 'zone_id', name: 'zone_def_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'zone_def_zone_id_key', constraint: 'unique', columns: ['zoneId'] },
    ],
  }, ZoneDefRow),
  my_conversation: __table({
    name: 'my_conversation',
    indexes: [
    ],
    constraints: [
    ],
  }, MyConversationRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_challenge", AcceptChallengeReducer),
  __reducerSchema("advance_dialogue", AdvanceDialogueReducer),
  __reducerSchema("attempt_recruit", AttemptRecruitReducer),
  __reducerSchema("buy", BuyReducer),
  __reducerSchema("cancel_challenge", CancelChallengeReducer),
  __reducerSchema("cancel_trade", CancelTradeReducer),
  __reducerSchema("care", CareReducer),
  __reducerSchema("challenge_pvp", ChallengePvpReducer),
  __reducerSchema("clear_queue", ClearQueueReducer),
  __reducerSchema("confirm_trade", ConfirmTradeReducer),
  __reducerSchema("decline_challenge", DeclineChallengeReducer),
  __reducerSchema("dismiss_dialogue", DismissDialogueReducer),
  __reducerSchema("enqueue_move", EnqueueMoveReducer),
  __reducerSchema("evolve", EvolveReducer),
  __reducerSchema("flee", FleeReducer),
  __reducerSchema("fuse", FuseReducer),
  __reducerSchema("heal_party", HealPartyReducer),
  __reducerSchema("join_game", JoinGameReducer),
  __reducerSchema("propose_trade", ProposeTradeReducer),
  __reducerSchema("respond_trade", RespondTradeReducer),
  __reducerSchema("sell", SellReducer),
  __reducerSchema("set_move", SetMoveReducer),
  __reducerSchema("set_nickname", SetNicknameReducer),
  __reducerSchema("set_party_slot", SetPartySlotReducer),
  __reducerSchema("set_profile_name", SetProfileNameReducer),
  __reducerSchema("start_battle", StartBattleReducer),
  __reducerSchema("submit_attack", SubmitAttackReducer),
  __reducerSchema("submit_pvp_action", SubmitPvpActionReducer),
  __reducerSchema("swap_active", SwapActiveReducer),
  __reducerSchema("sync_content", SyncContentReducer),
  __reducerSchema("talk", TalkReducer),
  __reducerSchema("train", TrainReducer),
  __reducerSchema("use_battle_item", UseBattleItemReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

