// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.1 (commit 4d9aa49594d59bf09f949b83c30413e43bf0805a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptChallengeReducer from "./accept_challenge_reducer";
import AdvanceDialogueReducer from "./advance_dialogue_reducer";
import AttemptRecruitReducer from "./attempt_recruit_reducer";
import BuyReducer from "./buy_reducer";
import CancelAccountDeletionReducer from "./cancel_account_deletion_reducer";
import CancelChallengeReducer from "./cancel_challenge_reducer";
import CancelTradeReducer from "./cancel_trade_reducer";
import CareReducer from "./care_reducer";
import ChallengePvpReducer from "./challenge_pvp_reducer";
import ClearQueueReducer from "./clear_queue_reducer";
import CompleteGuestClaimReducer from "./complete_guest_claim_reducer";
import ConfirmTradeReducer from "./confirm_trade_reducer";
import ConsumeCrystalizedEssenceReducer from "./consume_crystalized_essence_reducer";
import DeclineChallengeReducer from "./decline_challenge_reducer";
import DeleteAccountReducer from "./delete_account_reducer";
import DismissDialogueReducer from "./dismiss_dialogue_reducer";
import EnqueueMoveReducer from "./enqueue_move_reducer";
import EssenceTrainReducer from "./essence_train_reducer";
import EvolveReducer from "./evolve_reducer";
import FleeReducer from "./flee_reducer";
import HealPartyReducer from "./heal_party_reducer";
import JoinGameReducer from "./join_game_reducer";
import ProposeTradeReducer from "./propose_trade_reducer";
import RespondTradeReducer from "./respond_trade_reducer";
import SellReducer from "./sell_reducer";
import SetMoveReducer from "./set_move_reducer";
import SetNicknameReducer from "./set_nickname_reducer";
import SetPartySlotReducer from "./set_party_slot_reducer";
import SetProfileNameReducer from "./set_profile_name_reducer";
import StartBattleReducer from "./start_battle_reducer";
import StartGuestClaimReducer from "./start_guest_claim_reducer";
import SubmitAttackReducer from "./submit_attack_reducer";
import SubmitPvpActionReducer from "./submit_pvp_action_reducer";
import SwapActiveReducer from "./swap_active_reducer";
import SyncContentReducer from "./sync_content_reducer";
import TalkReducer from "./talk_reducer";
import TrainReducer from "./train_reducer";
import UseBattleItemReducer from "./use_battle_item_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BattleChallengeRow from "./battle_challenge_table";
import CharacterRow from "./character_table";
import ConfigRow from "./config_table";
import EvolutionPathRow from "./evolution_path_table";
import HealLocationRowRow from "./heal_location_row_table";
import InventoryRow from "./inventory_table";
import ItemRowRow from "./item_row_table";
import MyAccountRow from "./my_account_table";
import MyBattleRow from "./my_battle_table";
import MyConversationRow from "./my_conversation_table";
import MyMonsterPubRow from "./my_monster_pub_table";
import MyWalletRow from "./my_wallet_table";
import NpcRow from "./npc_table";
import PlayerRow from "./player_table";
import PlayerQuestRow from "./player_quest_table";
import ProfileRow from "./profile_table";
import ShopItemRowRow from "./shop_item_row_table";
import ShopRowRow from "./shop_row_table";
import SkillRowRow from "./skill_row_table";
import SpeciesRowRow from "./species_row_table";
import TradeOfferRow from "./trade_offer_table";
import TypeRelationRowRow from "./type_relation_row_table";
import ZoneDefRow from "./zone_def_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  battleChallenge: __table({
    name: 'battle_challenge',
    indexes: [
      { accessor: 'challenge_id', name: 'battle_challenge_challenge_id_idx_btree', algorithm: 'btree', columns: [
        'challengeId',
      ] },
      { accessor: 'challenger', name: 'battle_challenge_challenger_idx_btree', algorithm: 'btree', columns: [
        'challenger',
      ] },
      { accessor: 'target', name: 'battle_challenge_target_idx_btree', algorithm: 'btree', columns: [
        'target',
      ] },
    ],
    constraints: [
      { name: 'battle_challenge_challenge_id_key', constraint: 'unique', columns: ['challengeId'] },
    ],
  }, BattleChallengeRow),
  character: __table({
    name: 'character',
    indexes: [
      { accessor: 'entity_id', name: 'character_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'zone_id', name: 'character_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'character_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CharacterRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'id', name: 'config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConfigRow),
  evolutionPath: __table({
    name: 'evolution_path',
    indexes: [
      { accessor: 'from_species', name: 'evolution_path_from_species_idx_btree', algorithm: 'btree', columns: [
        'fromSpecies',
      ] },
      { accessor: 'path_id', name: 'evolution_path_path_id_idx_btree', algorithm: 'btree', columns: [
        'pathId',
      ] },
    ],
    constraints: [
      { name: 'evolution_path_path_id_key', constraint: 'unique', columns: ['pathId'] },
    ],
  }, EvolutionPathRow),
  healLocationRow: __table({
    name: 'heal_location_row',
    indexes: [
      { accessor: 'location_id', name: 'heal_location_row_location_id_idx_btree', algorithm: 'btree', columns: [
        'locationId',
      ] },
      { accessor: 'zone_id', name: 'heal_location_row_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'heal_location_row_location_id_key', constraint: 'unique', columns: ['locationId'] },
    ],
  }, HealLocationRowRow),
  inventory: __table({
    name: 'inventory',
    indexes: [
      { accessor: 'inv_id', name: 'inventory_inv_id_idx_btree', algorithm: 'btree', columns: [
        'invId',
      ] },
      { accessor: 'owner_identity', name: 'inventory_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
    ],
    constraints: [
      { name: 'inventory_inv_id_key', constraint: 'unique', columns: ['invId'] },
    ],
  }, InventoryRow),
  itemRow: __table({
    name: 'item_row',
    indexes: [
      { accessor: 'id', name: 'item_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'item_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemRowRow),
  npc: __table({
    name: 'npc',
    indexes: [
      { accessor: 'entity_id', name: 'npc_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'npc_id', name: 'npc_npc_id_idx_btree', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { accessor: 'zone_id', name: 'npc_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'npc_entity_id_key', constraint: 'unique', columns: ['entityId'] },
      { name: 'npc_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'entity_id', name: 'player_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerQuest: __table({
    name: 'player_quest',
    indexes: [
      { accessor: 'owner_identity', name: 'player_quest_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
      { accessor: 'pq_id', name: 'player_quest_pq_id_idx_btree', algorithm: 'btree', columns: [
        'pqId',
      ] },
    ],
    constraints: [
      { name: 'player_quest_pq_id_key', constraint: 'unique', columns: ['pqId'] },
    ],
  }, PlayerQuestRow),
  profile: __table({
    name: 'profile',
    indexes: [
      { accessor: 'identity', name: 'profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ProfileRow),
  shopItemRow: __table({
    name: 'shop_item_row',
    indexes: [
      { accessor: 'shop_id', name: 'shop_item_row_shop_id_idx_btree', algorithm: 'btree', columns: [
        'shopId',
      ] },
      { accessor: 'shop_item_id', name: 'shop_item_row_shop_item_id_idx_btree', algorithm: 'btree', columns: [
        'shopItemId',
      ] },
    ],
    constraints: [
      { name: 'shop_item_row_shop_item_id_key', constraint: 'unique', columns: ['shopItemId'] },
    ],
  }, ShopItemRowRow),
  shopRow: __table({
    name: 'shop_row',
    indexes: [
      { accessor: 'shop_id', name: 'shop_row_shop_id_idx_btree', algorithm: 'btree', columns: [
        'shopId',
      ] },
    ],
    constraints: [
      { name: 'shop_row_shop_id_key', constraint: 'unique', columns: ['shopId'] },
    ],
  }, ShopRowRow),
  skillRow: __table({
    name: 'skill_row',
    indexes: [
      { accessor: 'id', name: 'skill_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'skill_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SkillRowRow),
  speciesRow: __table({
    name: 'species_row',
    indexes: [
      { accessor: 'id', name: 'species_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'species_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpeciesRowRow),
  tradeOffer: __table({
    name: 'trade_offer',
    indexes: [
      { accessor: 'counterparty', name: 'trade_offer_counterparty_idx_btree', algorithm: 'btree', columns: [
        'counterparty',
      ] },
      { accessor: 'initiator', name: 'trade_offer_initiator_idx_btree', algorithm: 'btree', columns: [
        'initiator',
      ] },
      { accessor: 'trade_id', name: 'trade_offer_trade_id_idx_btree', algorithm: 'btree', columns: [
        'tradeId',
      ] },
    ],
    constraints: [
      { name: 'trade_offer_trade_id_key', constraint: 'unique', columns: ['tradeId'] },
    ],
  }, TradeOfferRow),
  typeRelationRow: __table({
    name: 'type_relation_row',
    indexes: [
      { accessor: 'id', name: 'type_relation_row_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'type_relation_row_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TypeRelationRowRow),
  zoneDef: __table({
    name: 'zone_def',
    indexes: [
      { accessor: 'zone_id', name: 'zone_def_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'zone_def_zone_id_key', constraint: 'unique', columns: ['zoneId'] },
    ],
  }, ZoneDefRow),
  myAccount: __table({
    name: 'my_account',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccountRow),
  myBattle: __table({
    name: 'my_battle',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBattleRow),
  myConversation: __table({
    name: 'my_conversation',
    indexes: [
    ],
    constraints: [
    ],
  }, MyConversationRow),
  myMonsterPub: __table({
    name: 'my_monster_pub',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMonsterPubRow),
  myWallet: __table({
    name: 'my_wallet',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWalletRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_challenge", AcceptChallengeReducer),
  __reducerSchema("advance_dialogue", AdvanceDialogueReducer),
  __reducerSchema("attempt_recruit", AttemptRecruitReducer),
  __reducerSchema("buy", BuyReducer),
  __reducerSchema("cancel_account_deletion", CancelAccountDeletionReducer),
  __reducerSchema("cancel_challenge", CancelChallengeReducer),
  __reducerSchema("cancel_trade", CancelTradeReducer),
  __reducerSchema("care", CareReducer),
  __reducerSchema("challenge_pvp", ChallengePvpReducer),
  __reducerSchema("clear_queue", ClearQueueReducer),
  __reducerSchema("complete_guest_claim", CompleteGuestClaimReducer),
  __reducerSchema("confirm_trade", ConfirmTradeReducer),
  __reducerSchema("consume_crystalized_essence", ConsumeCrystalizedEssenceReducer),
  __reducerSchema("decline_challenge", DeclineChallengeReducer),
  __reducerSchema("delete_account", DeleteAccountReducer),
  __reducerSchema("dismiss_dialogue", DismissDialogueReducer),
  __reducerSchema("enqueue_move", EnqueueMoveReducer),
  __reducerSchema("essence_train", EssenceTrainReducer),
  __reducerSchema("evolve", EvolveReducer),
  __reducerSchema("flee", FleeReducer),
  __reducerSchema("heal_party", HealPartyReducer),
  __reducerSchema("join_game", JoinGameReducer),
  __reducerSchema("propose_trade", ProposeTradeReducer),
  __reducerSchema("respond_trade", RespondTradeReducer),
  __reducerSchema("sell", SellReducer),
  __reducerSchema("set_move", SetMoveReducer),
  __reducerSchema("set_nickname", SetNicknameReducer),
  __reducerSchema("set_party_slot", SetPartySlotReducer),
  __reducerSchema("set_profile_name", SetProfileNameReducer),
  __reducerSchema("start_battle", StartBattleReducer),
  __reducerSchema("start_guest_claim", StartGuestClaimReducer),
  __reducerSchema("submit_attack", SubmitAttackReducer),
  __reducerSchema("submit_pvp_action", SubmitPvpActionReducer),
  __reducerSchema("swap_active", SwapActiveReducer),
  __reducerSchema("sync_content", SyncContentReducer),
  __reducerSchema("talk", TalkReducer),
  __reducerSchema("train", TrainReducer),
  __reducerSchema("use_battle_item", UseBattleItemReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `battleChallenge` instead. This alias will be removed in the next major version. */
    readonly "battle_challenge": Omit<typeof tablesSchema.schemaType.tables["battleChallenge"], "accessorName"> & { readonly accessorName: "battle_challenge" };
    /** @deprecated Use `evolutionPath` instead. This alias will be removed in the next major version. */
    readonly "evolution_path": Omit<typeof tablesSchema.schemaType.tables["evolutionPath"], "accessorName"> & { readonly accessorName: "evolution_path" };
    /** @deprecated Use `healLocationRow` instead. This alias will be removed in the next major version. */
    readonly "heal_location_row": Omit<typeof tablesSchema.schemaType.tables["healLocationRow"], "accessorName"> & { readonly accessorName: "heal_location_row" };
    /** @deprecated Use `itemRow` instead. This alias will be removed in the next major version. */
    readonly "item_row": Omit<typeof tablesSchema.schemaType.tables["itemRow"], "accessorName"> & { readonly accessorName: "item_row" };
    /** @deprecated Use `playerQuest` instead. This alias will be removed in the next major version. */
    readonly "player_quest": Omit<typeof tablesSchema.schemaType.tables["playerQuest"], "accessorName"> & { readonly accessorName: "player_quest" };
    /** @deprecated Use `shopItemRow` instead. This alias will be removed in the next major version. */
    readonly "shop_item_row": Omit<typeof tablesSchema.schemaType.tables["shopItemRow"], "accessorName"> & { readonly accessorName: "shop_item_row" };
    /** @deprecated Use `shopRow` instead. This alias will be removed in the next major version. */
    readonly "shop_row": Omit<typeof tablesSchema.schemaType.tables["shopRow"], "accessorName"> & { readonly accessorName: "shop_row" };
    /** @deprecated Use `skillRow` instead. This alias will be removed in the next major version. */
    readonly "skill_row": Omit<typeof tablesSchema.schemaType.tables["skillRow"], "accessorName"> & { readonly accessorName: "skill_row" };
    /** @deprecated Use `speciesRow` instead. This alias will be removed in the next major version. */
    readonly "species_row": Omit<typeof tablesSchema.schemaType.tables["speciesRow"], "accessorName"> & { readonly accessorName: "species_row" };
    /** @deprecated Use `tradeOffer` instead. This alias will be removed in the next major version. */
    readonly "trade_offer": Omit<typeof tablesSchema.schemaType.tables["tradeOffer"], "accessorName"> & { readonly accessorName: "trade_offer" };
    /** @deprecated Use `typeRelationRow` instead. This alias will be removed in the next major version. */
    readonly "type_relation_row": Omit<typeof tablesSchema.schemaType.tables["typeRelationRow"], "accessorName"> & { readonly accessorName: "type_relation_row" };
    /** @deprecated Use `zoneDef` instead. This alias will be removed in the next major version. */
    readonly "zone_def": Omit<typeof tablesSchema.schemaType.tables["zoneDef"], "accessorName"> & { readonly accessorName: "zone_def" };
    /** @deprecated Use `myAccount` instead. This alias will be removed in the next major version. */
    readonly "my_account": Omit<typeof tablesSchema.schemaType.tables["myAccount"], "accessorName"> & { readonly accessorName: "my_account" };
    /** @deprecated Use `myBattle` instead. This alias will be removed in the next major version. */
    readonly "my_battle": Omit<typeof tablesSchema.schemaType.tables["myBattle"], "accessorName"> & { readonly accessorName: "my_battle" };
    /** @deprecated Use `myConversation` instead. This alias will be removed in the next major version. */
    readonly "my_conversation": Omit<typeof tablesSchema.schemaType.tables["myConversation"], "accessorName"> & { readonly accessorName: "my_conversation" };
    /** @deprecated Use `myMonsterPub` instead. This alias will be removed in the next major version. */
    readonly "my_monster_pub": Omit<typeof tablesSchema.schemaType.tables["myMonsterPub"], "accessorName"> & { readonly accessorName: "my_monster_pub" };
    /** @deprecated Use `myWallet` instead. This alias will be removed in the next major version. */
    readonly "my_wallet": Omit<typeof tablesSchema.schemaType.tables["myWallet"], "accessorName"> & { readonly accessorName: "my_wallet" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.1" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "battle_challenge": "battleChallenge",
  "evolution_path": "evolutionPath",
  "heal_location_row": "healLocationRow",
  "item_row": "itemRow",
  "player_quest": "playerQuest",
  "shop_item_row": "shopItemRow",
  "shop_row": "shopRow",
  "skill_row": "skillRow",
  "species_row": "speciesRow",
  "trade_offer": "tradeOffer",
  "type_relation_row": "typeRelationRow",
  "zone_def": "zoneDef",
  "my_account": "myAccount",
  "my_battle": "myBattle",
  "my_conversation": "myConversation",
  "my_monster_pub": "myMonsterPub",
  "my_wallet": "myWallet",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `battleChallenge` instead. This alias will be removed in the next major version. */
  readonly "battle_challenge": __DbViewBase["battleChallenge"];
  /** @deprecated Use `evolutionPath` instead. This alias will be removed in the next major version. */
  readonly "evolution_path": __DbViewBase["evolutionPath"];
  /** @deprecated Use `healLocationRow` instead. This alias will be removed in the next major version. */
  readonly "heal_location_row": __DbViewBase["healLocationRow"];
  /** @deprecated Use `itemRow` instead. This alias will be removed in the next major version. */
  readonly "item_row": __DbViewBase["itemRow"];
  /** @deprecated Use `playerQuest` instead. This alias will be removed in the next major version. */
  readonly "player_quest": __DbViewBase["playerQuest"];
  /** @deprecated Use `shopItemRow` instead. This alias will be removed in the next major version. */
  readonly "shop_item_row": __DbViewBase["shopItemRow"];
  /** @deprecated Use `shopRow` instead. This alias will be removed in the next major version. */
  readonly "shop_row": __DbViewBase["shopRow"];
  /** @deprecated Use `skillRow` instead. This alias will be removed in the next major version. */
  readonly "skill_row": __DbViewBase["skillRow"];
  /** @deprecated Use `speciesRow` instead. This alias will be removed in the next major version. */
  readonly "species_row": __DbViewBase["speciesRow"];
  /** @deprecated Use `tradeOffer` instead. This alias will be removed in the next major version. */
  readonly "trade_offer": __DbViewBase["tradeOffer"];
  /** @deprecated Use `typeRelationRow` instead. This alias will be removed in the next major version. */
  readonly "type_relation_row": __DbViewBase["typeRelationRow"];
  /** @deprecated Use `zoneDef` instead. This alias will be removed in the next major version. */
  readonly "zone_def": __DbViewBase["zoneDef"];
  /** @deprecated Use `myAccount` instead. This alias will be removed in the next major version. */
  readonly "my_account": __DbViewBase["myAccount"];
  /** @deprecated Use `myBattle` instead. This alias will be removed in the next major version. */
  readonly "my_battle": __DbViewBase["myBattle"];
  /** @deprecated Use `myConversation` instead. This alias will be removed in the next major version. */
  readonly "my_conversation": __DbViewBase["myConversation"];
  /** @deprecated Use `myMonsterPub` instead. This alias will be removed in the next major version. */
  readonly "my_monster_pub": __DbViewBase["myMonsterPub"];
  /** @deprecated Use `myWallet` instead. This alias will be removed in the next major version. */
  readonly "my_wallet": __DbViewBase["myWallet"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `battleChallenge` instead. This alias will be removed in the next major version. */
  readonly "battle_challenge": __TablesBase["battleChallenge"];
  /** @deprecated Use `evolutionPath` instead. This alias will be removed in the next major version. */
  readonly "evolution_path": __TablesBase["evolutionPath"];
  /** @deprecated Use `healLocationRow` instead. This alias will be removed in the next major version. */
  readonly "heal_location_row": __TablesBase["healLocationRow"];
  /** @deprecated Use `itemRow` instead. This alias will be removed in the next major version. */
  readonly "item_row": __TablesBase["itemRow"];
  /** @deprecated Use `playerQuest` instead. This alias will be removed in the next major version. */
  readonly "player_quest": __TablesBase["playerQuest"];
  /** @deprecated Use `shopItemRow` instead. This alias will be removed in the next major version. */
  readonly "shop_item_row": __TablesBase["shopItemRow"];
  /** @deprecated Use `shopRow` instead. This alias will be removed in the next major version. */
  readonly "shop_row": __TablesBase["shopRow"];
  /** @deprecated Use `skillRow` instead. This alias will be removed in the next major version. */
  readonly "skill_row": __TablesBase["skillRow"];
  /** @deprecated Use `speciesRow` instead. This alias will be removed in the next major version. */
  readonly "species_row": __TablesBase["speciesRow"];
  /** @deprecated Use `tradeOffer` instead. This alias will be removed in the next major version. */
  readonly "trade_offer": __TablesBase["tradeOffer"];
  /** @deprecated Use `typeRelationRow` instead. This alias will be removed in the next major version. */
  readonly "type_relation_row": __TablesBase["typeRelationRow"];
  /** @deprecated Use `zoneDef` instead. This alias will be removed in the next major version. */
  readonly "zone_def": __TablesBase["zoneDef"];
  /** @deprecated Use `myAccount` instead. This alias will be removed in the next major version. */
  readonly "my_account": __TablesBase["myAccount"];
  /** @deprecated Use `myBattle` instead. This alias will be removed in the next major version. */
  readonly "my_battle": __TablesBase["myBattle"];
  /** @deprecated Use `myConversation` instead. This alias will be removed in the next major version. */
  readonly "my_conversation": __TablesBase["myConversation"];
  /** @deprecated Use `myMonsterPub` instead. This alias will be removed in the next major version. */
  readonly "my_monster_pub": __TablesBase["myMonsterPub"];
  /** @deprecated Use `myWallet` instead. This alias will be removed in the next major version. */
  readonly "my_wallet": __TablesBase["myWallet"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

