// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  StatKind,
  StatusKind,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  recruitBonus: __t.u16().name("recruit_bonus"),
  get trainStat() {
    return __t.option(StatKind).name("train_stat");
  },
  trainAmount: __t.u16().name("train_amount"),
  sellPrice: __t.u64().name("sell_price"),
  get cureStatus() {
    return __t.option(StatusKind).name("cure_status");
  },
});
