// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  monsterId: __t.u64().primaryKey().name("monster_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  speciesId: __t.u32().name("species_id"),
  nickname: __t.string(),
  level: __t.u8(),
  xp: __t.u32(),
  bond: __t.u8(),
  currentHp: __t.u16().name("current_hp"),
  statHp: __t.u16().name("stat_hp"),
  statAttack: __t.u16().name("stat_attack"),
  statDefense: __t.u16().name("stat_defense"),
  statSpeed: __t.u16().name("stat_speed"),
  statSpAttack: __t.u16().name("stat_sp_attack"),
  statSpDefense: __t.u16().name("stat_sp_defense"),
  partySlot: __t.u8().name("party_slot"),
});
