// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AccountStatus,
} from "./types";


export default __t.row({
  identity: __t.identity(),
  authIssuer: __t.string().name("auth_issuer"),
  createdAtMs: __t.i64().name("created_at_ms"),
  lastLoginAtMs: __t.i64().name("last_login_at_ms"),
  get status() {
    return AccountStatus;
  },
  deletionRequestedAtMs: __t.option(__t.i64()).name("deletion_requested_at_ms"),
  claimedFrom: __t.option(__t.identity()).name("claimed_from"),
  claimedAtMs: __t.option(__t.i64()).name("claimed_at_ms"),
});
