// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkId: __t.u64().name("chunk_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  requestId: __t.u64().name("request_id"),
  tableName: __t.string().name("table_name"),
  chunkIndex: __t.u32().name("chunk_index"),
  totalChunks: __t.u32().name("total_chunks"),
  payloadJson: __t.string().name("payload_json"),
  createdAtMs: __t.i64().name("created_at_ms"),
});
