// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  npcId: __t.string().name("npc_id"),
  zoneId: __t.u32().name("zone_id"),
  homeX: __t.i32().name("home_x"),
  homeY: __t.i32().name("home_y"),
  wanderRadius: __t.u8().name("wander_radius"),
  dialogueTreeId: __t.string().name("dialogue_tree_id"),
});
