// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  zoneId: __t.u32().name("zone_id"),
  tileX: __t.i32().name("tile_x"),
  tileY: __t.i32().name("tile_y"),
  name: __t.string(),
  lastSeenMs: __t.i64().name("last_seen_ms"),
});
