// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TradeItem,
} from "./types";

export default {
  counterparty: __t.identity(),
  initiatorMonsterIds: __t.array(__t.u64()),
  get initiatorItems() {
    return __t.array(TradeItem);
  },
  initiatorCurrency: __t.u64(),
  counterpartyMonsterIds: __t.array(__t.u64()),
  get counterpartyItems() {
    return __t.array(TradeItem);
  },
  counterpartyCurrency: __t.u64(),
};
