// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  shopItemId: __t.u64().primaryKey().name("shop_item_id"),
  shopId: __t.u32().name("shop_id"),
  itemId: __t.u32().name("item_id"),
  buyPrice: __t.u64().name("buy_price"),
});
