// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Affinity,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  baseHp: __t.u16().name("base_hp"),
  baseAttack: __t.u16().name("base_attack"),
  baseDefense: __t.u16().name("base_defense"),
  baseSpeed: __t.u16().name("base_speed"),
  baseSpAttack: __t.u16().name("base_sp_attack"),
  baseSpDefense: __t.u16().name("base_sp_defense"),
  get affinity() {
    return Affinity;
  },
  learnableSkillIds: __t.array(__t.u32()).name("learnable_skill_ids"),
  ability: __t.option(__t.u32()),
});
