// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TradeItem,
  MonsterCard,
  TradeStatus,
} from "./types";


export default __t.row({
  tradeId: __t.u64().primaryKey().name("trade_id"),
  initiator: __t.identity(),
  counterparty: __t.identity(),
  initiatorMonsterIds: __t.array(__t.u64()).name("initiator_monster_ids"),
  get initiatorItems() {
    return __t.array(TradeItem).name("initiator_items");
  },
  initiatorCurrency: __t.u64().name("initiator_currency"),
  counterpartyMonsterIds: __t.array(__t.u64()).name("counterparty_monster_ids"),
  get counterpartyItems() {
    return __t.array(TradeItem).name("counterparty_items");
  },
  counterpartyCurrency: __t.u64().name("counterparty_currency"),
  get initiatorCards() {
    return __t.array(MonsterCard).name("initiator_cards");
  },
  get counterpartyCards() {
    return __t.array(MonsterCard).name("counterparty_cards");
  },
  get status() {
    return TradeStatus;
  },
  createdAtMs: __t.i64().name("created_at_ms"),
});
