// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Config = __t.object("Config", {
  id: __t.u32(),
  contentVersion: __t.u32(),
});
export type Config = __Infer<typeof Config>;

export const Presence = __t.object("Presence", {
  identity: __t.identity(),
  zoneId: __t.u32(),
  tileX: __t.i32(),
  tileY: __t.i32(),
  name: __t.string(),
  lastSeenMs: __t.i64(),
});
export type Presence = __Infer<typeof Presence>;

export const PresenceReaperSchedule = __t.object("PresenceReaperSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PresenceReaperSchedule = __Infer<typeof PresenceReaperSchedule>;

export const ZoneDefRow = __t.object("ZoneDefRow", {
  zoneId: __t.u32(),
  name: __t.string(),
  width: __t.u32(),
  height: __t.u32(),
});
export type ZoneDefRow = __Infer<typeof ZoneDefRow>;

