// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ActionState`.
export const ActionState = __t.enum("ActionState", {
  Idle: __t.unit(),
  Walking: __t.unit(),
  Jumping: __t.unit(),
});
export type ActionState = __Infer<typeof ActionState>;

// The tagged union or sum type for the algebraic type `Affinity`.
export const Affinity = __t.enum("Affinity", {
  Fire: __t.unit(),
  Water: __t.unit(),
  Plant: __t.unit(),
  Electric: __t.unit(),
  Earth: __t.unit(),
  Wind: __t.unit(),
  Light: __t.unit(),
  Dark: __t.unit(),
});
export type Affinity = __Infer<typeof Affinity>;

export const Battle = __t.object("Battle", {
  battleId: __t.u64(),
  playerIdentity: __t.identity(),
  opponentIdentity: __t.identity(),
  get state() {
    return BattleState;
  },
  partyMonsterIds: __t.array(__t.u64()),
  opponentMonsterIds: __t.array(__t.u64()),
  createdAtMs: __t.i64(),
});
export type Battle = __Infer<typeof Battle>;

export const BattleMonster = __t.object("BattleMonster", {
  speciesId: __t.u32(),
  get affinity() {
    return Affinity;
  },
  level: __t.u8(),
  currentHp: __t.u16(),
  maxHp: __t.u16(),
  get stats() {
    return StatBlock;
  },
  knownSkillIds: __t.array(__t.u32()),
  get status() {
    return __t.option(StatusEffect);
  },
});
export type BattleMonster = __Infer<typeof BattleMonster>;

// The tagged union or sum type for the algebraic type `BattleOutcome`.
export const BattleOutcome = __t.enum("BattleOutcome", {
  Ongoing: __t.unit(),
  SideAWins: __t.unit(),
  SideBWins: __t.unit(),
  Fled: __t.unit(),
});
export type BattleOutcome = __Infer<typeof BattleOutcome>;

export const BattleSide = __t.object("BattleSide", {
  active: __t.u32(),
  get team() {
    return __t.array(BattleMonster);
  },
});
export type BattleSide = __Infer<typeof BattleSide>;

export const BattleState = __t.object("BattleState", {
  get sideA() {
    return BattleSide;
  },
  get sideB() {
    return BattleSide;
  },
  get outcome() {
    return BattleOutcome;
  },
  turnNumber: __t.u16(),
  get weather() {
    return __t.option(WeatherEffect);
  },
});
export type BattleState = __Infer<typeof BattleState>;

export const BattleWild = __t.object("BattleWild", {
  battleId: __t.u64(),
  wildSpeciesId: __t.u32(),
  wildLevel: __t.u8(),
  individualitySeed: __t.u32(),
});
export type BattleWild = __Infer<typeof BattleWild>;

export const Character = __t.object("Character", {
  entityId: __t.u64(),
  zoneId: __t.u32(),
  tileX: __t.i32(),
  tileY: __t.i32(),
  get facing() {
    return Direction;
  },
  get action() {
    return ActionState;
  },
  moveStartedAtMs: __t.i64(),
  spriteId: __t.u32(),
  get moveQueue() {
    return __t.array(MoveInput);
  },
});
export type Character = __Infer<typeof Character>;

export const Config = __t.object("Config", {
  id: __t.u32(),
  contentVersion: __t.u32(),
  ownerIdentity: __t.identity(),
});
export type Config = __Infer<typeof Config>;

// The tagged union or sum type for the algebraic type `Direction`.
export const Direction = __t.enum("Direction", {
  North: __t.unit(),
  South: __t.unit(),
  East: __t.unit(),
  West: __t.unit(),
});
export type Direction = __Infer<typeof Direction>;

export const EncounterEntryRow = __t.object("EncounterEntryRow", {
  speciesId: __t.u32(),
  weight: __t.u16(),
  minLevel: __t.u8(),
  maxLevel: __t.u8(),
});
export type EncounterEntryRow = __Infer<typeof EncounterEntryRow>;

export const EncounterRow = __t.object("EncounterRow", {
  zoneId: __t.u32(),
  encounterRate: __t.u16(),
  get entries() {
    return __t.array(EncounterEntryRow);
  },
});
export type EncounterRow = __Infer<typeof EncounterRow>;

export const Fusion = __t.object("Fusion", {
  fusionId: __t.u64(),
  aSpecies: __t.u32(),
  bSpecies: __t.u32(),
  toSpecies: __t.u32(),
});
export type Fusion = __Infer<typeof Fusion>;

export const HealCooldown = __t.object("HealCooldown", {
  ownerIdentity: __t.identity(),
  lastHealAtMs: __t.i64(),
});
export type HealCooldown = __Infer<typeof HealCooldown>;

export const HealLocationRow = __t.object("HealLocationRow", {
  locationId: __t.u32(),
  zoneId: __t.u32(),
  tileX: __t.i32(),
  tileY: __t.i32(),
  costItemId: __t.option(__t.u32()),
  costQty: __t.u32(),
  cooldownMs: __t.i64(),
});
export type HealLocationRow = __Infer<typeof HealLocationRow>;

export const Inventory = __t.object("Inventory", {
  invId: __t.u64(),
  ownerIdentity: __t.identity(),
  itemId: __t.u32(),
  count: __t.u32(),
});
export type Inventory = __Infer<typeof Inventory>;

export const ItemRow = __t.object("ItemRow", {
  id: __t.u32(),
  name: __t.string(),
  description: __t.string(),
  recruitBonus: __t.u16(),
  get trainStat() {
    return __t.option(StatKind);
  },
  trainAmount: __t.u16(),
  sellPrice: __t.u64(),
  get cureStatus() {
    return __t.option(StatusKind);
  },
});
export type ItemRow = __Infer<typeof ItemRow>;

export const Monster = __t.object("Monster", {
  monsterId: __t.u64(),
  ownerIdentity: __t.identity(),
  speciesId: __t.u32(),
  nickname: __t.string(),
  level: __t.u8(),
  xp: __t.u32(),
  bond: __t.u8(),
  ivHp: __t.u8(),
  ivAttack: __t.u8(),
  ivDefense: __t.u8(),
  ivSpeed: __t.u8(),
  ivSpAttack: __t.u8(),
  ivSpDefense: __t.u8(),
  get natureKind() {
    return NatureKind;
  },
  evHp: __t.u16(),
  evAttack: __t.u16(),
  evDefense: __t.u16(),
  evSpeed: __t.u16(),
  evSpAttack: __t.u16(),
  evSpDefense: __t.u16(),
  statHp: __t.u16(),
  statAttack: __t.u16(),
  statDefense: __t.u16(),
  statSpeed: __t.u16(),
  statSpAttack: __t.u16(),
  statSpDefense: __t.u16(),
  currentHp: __t.u16(),
  partySlot: __t.u8(),
  lastCareAtMs: __t.i64(),
  evolvesTo: __t.option(__t.u32()),
});
export type Monster = __Infer<typeof Monster>;

export const MonsterPub = __t.object("MonsterPub", {
  monsterId: __t.u64(),
  ownerIdentity: __t.identity(),
  speciesId: __t.u32(),
  nickname: __t.string(),
  level: __t.u8(),
  xp: __t.u32(),
  bond: __t.u8(),
  currentHp: __t.u16(),
  statHp: __t.u16(),
  statAttack: __t.u16(),
  statDefense: __t.u16(),
  statSpeed: __t.u16(),
  statSpAttack: __t.u16(),
  statSpDefense: __t.u16(),
  partySlot: __t.u8(),
  evolvesTo: __t.option(__t.u32()),
});
export type MonsterPub = __Infer<typeof MonsterPub>;

// The tagged union or sum type for the algebraic type `MoveInput`.
export const MoveInput = __t.enum("MoveInput", {
  get Step() {
    return Direction;
  },
  Jump: __t.unit(),
});
export type MoveInput = __Infer<typeof MoveInput>;

export const MovementTickSchedule = __t.object("MovementTickSchedule", {
  id: __t.u64(),
  zoneId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type MovementTickSchedule = __Infer<typeof MovementTickSchedule>;

// The tagged union or sum type for the algebraic type `NatureKind`.
export const NatureKind = __t.enum("NatureKind", {
  Hardy: __t.unit(),
  Lonely: __t.unit(),
  Brave: __t.unit(),
  Adamant: __t.unit(),
  Naughty: __t.unit(),
  Bold: __t.unit(),
  Docile: __t.unit(),
  Relaxed: __t.unit(),
  Impish: __t.unit(),
  Lax: __t.unit(),
  Timid: __t.unit(),
  Hasty: __t.unit(),
  Serious: __t.unit(),
  Jolly: __t.unit(),
  Naive: __t.unit(),
  Modest: __t.unit(),
  Mild: __t.unit(),
  Quiet: __t.unit(),
  Bashful: __t.unit(),
  Rash: __t.unit(),
  Calm: __t.unit(),
  Gentle: __t.unit(),
  Sassy: __t.unit(),
  Careful: __t.unit(),
  Quirky: __t.unit(),
});
export type NatureKind = __Infer<typeof NatureKind>;

export const Npc = __t.object("Npc", {
  entityId: __t.u64(),
  npcId: __t.string(),
  zoneId: __t.u32(),
  homeX: __t.i32(),
  homeY: __t.i32(),
  wanderRadius: __t.u8(),
  dialogueTreeId: __t.string(),
});
export type Npc = __Infer<typeof Npc>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  entityId: __t.u64(),
  name: __t.string(),
  online: __t.bool(),
  lastInputSeq: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const PlayerConversation = __t.object("PlayerConversation", {
  ownerIdentity: __t.identity(),
  npcEntityId: __t.u64(),
  currentNodeId: __t.string(),
});
export type PlayerConversation = __Infer<typeof PlayerConversation>;

export const PlayerDialogueStateRow = __t.object("PlayerDialogueStateRow", {
  ownerIdentity: __t.identity(),
  flags: __t.array(__t.string()),
  doneQuests: __t.array(__t.string()),
});
export type PlayerDialogueStateRow = __Infer<typeof PlayerDialogueStateRow>;

export const PlayerQuestRow = __t.object("PlayerQuestRow", {
  pqId: __t.u64(),
  ownerIdentity: __t.identity(),
  questId: __t.string(),
  stepIndex: __t.u32(),
});
export type PlayerQuestRow = __Infer<typeof PlayerQuestRow>;

export const PlayerWallet = __t.object("PlayerWallet", {
  ownerIdentity: __t.identity(),
  balance: __t.u64(),
});
export type PlayerWallet = __Infer<typeof PlayerWallet>;

export const ShopItemRow = __t.object("ShopItemRow", {
  shopItemId: __t.u64(),
  shopId: __t.u32(),
  itemId: __t.u32(),
  buyPrice: __t.u64(),
});
export type ShopItemRow = __Infer<typeof ShopItemRow>;

export const ShopRow = __t.object("ShopRow", {
  shopId: __t.u32(),
  name: __t.string(),
});
export type ShopRow = __Infer<typeof ShopRow>;

export const SkillRow = __t.object("SkillRow", {
  id: __t.u32(),
  name: __t.string(),
  get affinity() {
    return Affinity;
  },
  power: __t.u16(),
  accuracy: __t.u8(),
  pp: __t.u8(),
});
export type SkillRow = __Infer<typeof SkillRow>;

export const SpeciesRow = __t.object("SpeciesRow", {
  id: __t.u32(),
  name: __t.string(),
  baseHp: __t.u16(),
  baseAttack: __t.u16(),
  baseDefense: __t.u16(),
  baseSpeed: __t.u16(),
  baseSpAttack: __t.u16(),
  baseSpDefense: __t.u16(),
  get affinity() {
    return Affinity;
  },
  learnableSkillIds: __t.array(__t.u32()),
  ability: __t.option(__t.u32()),
});
export type SpeciesRow = __Infer<typeof SpeciesRow>;

export const StatBlock = __t.object("StatBlock", {
  hp: __t.u16(),
  attack: __t.u16(),
  defense: __t.u16(),
  speed: __t.u16(),
  spAttack: __t.u16(),
  spDefense: __t.u16(),
});
export type StatBlock = __Infer<typeof StatBlock>;

// The tagged union or sum type for the algebraic type `StatKind`.
export const StatKind = __t.enum("StatKind", {
  Hp: __t.unit(),
  Attack: __t.unit(),
  Defense: __t.unit(),
  Speed: __t.unit(),
  SpAttack: __t.unit(),
  SpDefense: __t.unit(),
});
export type StatKind = __Infer<typeof StatKind>;

// The tagged union or sum type for the algebraic type `StatusEffect`.
export const StatusEffect = __t.enum("StatusEffect", {
  Poison: __t.unit(),
  Burn: __t.unit(),
  Paralysis: __t.unit(),
  Sleep: __t.u8(),
  Freeze: __t.unit(),
});
export type StatusEffect = __Infer<typeof StatusEffect>;

// The tagged union or sum type for the algebraic type `StatusKind`.
export const StatusKind = __t.enum("StatusKind", {
  Poison: __t.unit(),
  Burn: __t.unit(),
  Paralysis: __t.unit(),
  Sleep: __t.unit(),
  Freeze: __t.unit(),
});
export type StatusKind = __Infer<typeof StatusKind>;

export const TypeRelationRow = __t.object("TypeRelationRow", {
  id: __t.u64(),
  get attacker() {
    return Affinity;
  },
  get defender() {
    return Affinity;
  },
  effectiveness: __t.u8(),
});
export type TypeRelationRow = __Infer<typeof TypeRelationRow>;

// The tagged union or sum type for the algebraic type `WeatherEffect`.
export const WeatherEffect = __t.enum("WeatherEffect", {
  Rain: __t.u8(),
  Sun: __t.u8(),
  Sandstorm: __t.u8(),
  Hail: __t.u8(),
});
export type WeatherEffect = __Infer<typeof WeatherEffect>;

export const ZoneDefRow = __t.object("ZoneDefRow", {
  zoneId: __t.u32(),
  name: __t.string(),
  width: __t.u32(),
  height: __t.u32(),
});
export type ZoneDefRow = __Infer<typeof ZoneDefRow>;

