// scripts/adr-digest.test.mjs — rb-43 RED gate: the DERIVED "next free project
// ADR number" line that scripts/adr-digest.mjs must render into the generated
// docs/adr/DIGEST.md, replacing the hand-maintained digit in docs/adr/README.md.
//
// WHAT IS GATED (the frozen contract):
//   1. The rendered line, exact template. Non-empty corpus: NNNN = highest id on
//      disk plus one, MMMM = that highest id. EMPTY corpus: the WHOLE first
//      clause is swapped for `— no project ADRs on disk.` (not just a
//      parenthetical — `(highest on disk: none) plus one` is not English).
//      The line claims only checkable things: it is regenerated by
//      `just adr-digest` and drift-gated by `just ci`. It does NOT claim to be
//      "never hand-maintained" — that is unverifiable provenance.
//   2. Position: first non-empty line after the `Generated from ...` line,
//      separated by exactly one blank line, at column 0, outside any HTML
//      comment, and the ONLY bold-code number in the generated digest.
//   3. Band guard: any COLLECTED id outside 0001-0999 fails loud — in generate
//      AND in --check mode, before any write, naming the band on stderr.
//   4. The CLI is otherwise unchanged (--adr-dir / --out / --check), and the
//      derived line lives INSIDE the payload --check compares.
//   5. docs/adr/README.md hand-maintains no ADR number at all, and its
//      next-free paragraph still points at DIGEST.md (moved, not deleted).
//
// EXPECTED STATE AT RED: scripts/adr-digest.mjs renders no such line and has no
// band guard; docs/adr/README.md:16 still carries a hand-maintained four-digit
// number. All six tests fail. The tester does not implement the feature.
//
// SAFETY — every spawn passes BOTH --adr-dir AND --out into a mkdtemp dir, and
// `--adr-dir` IS THE LOAD-BEARING ONE: DIGEST_PATH defaults to
// join(ADR_DIR, 'DIGEST.md') (scripts/adr-digest.mjs:109), so a run with
// --adr-dir but no --out writes into the temp corpus dir, while a run with
// --out but no --adr-dir READS the real corpus (and a check-mode run compares
// against it). Do not relax --adr-dir. Every temp dir is removed in a
// `finally`. X5 and X6 only READ the real files; they never spawn.
//
// IMPORTANT: NO new RegExp(...) anywhere — the remote-only Semgrep rule
// detect-non-literal-regexp has bitten this project 3x. Literal /regex/ and
// String.includes/indexOf/startsWith only.
//
// X1/X4/X6 collect every fixture's outcome and assert ONCE on the collected
// array: `assert` throws on first failure, so a per-fixture assert would leave
// most of the corpora unmeasured on a red run.
//
// Runs as: node --test scripts/adr-digest.test.mjs   (from the repo root)

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SCRIPT = join(ROOT, 'scripts', 'adr-digest.mjs');
const REAL_ADR_DIR = join(ROOT, 'docs', 'adr');

/** The stable prefix of the derived line — the handle every assertion grabs. */
const MARKER = 'Next free project ADR number:';

/** Contract §3: the substring the band guard must print on stderr. */
const BAND_MESSAGE = 'outside the project ADR band 0001-0999';

/** Written into every band-guard run's --out target; must survive a loud failure. */
const SENTINEL = 'SENTINEL — a run that fails the band guard must not write this file.\n';

// ---------------------------------------------------------------------------
// Process helper — spawnSync so an exit code is data, not a throw. A spawn
// FAILURE (ENOENT, EMFILE) is folded into stderr so it can never be misread as
// a content failure.
// ---------------------------------------------------------------------------
function runDigest(args) {
  const result = spawnSync('node', [SCRIPT, ...args], {
    cwd: ROOT,
    encoding: 'utf8',
    stdio: 'pipe',
  });
  const spawnError = result.error ? `\n[spawn error] ${result.error.message}` : '';
  return {
    code: result.status !== null ? result.status : 1,
    stderr: `${result.stderr ?? ''}${spawnError}`,
    stdout: result.stdout ?? '',
  };
}

// ---------------------------------------------------------------------------
// Fixture builder — canonical header shape, copied from
// evals/fixtures/adr-digest/0900-good.md and checked against validateAdr():
// Status, Date, Slice, Supersedes, Amends, Subsystems, Decision are all
// required (LEGACY_TOLERANCE is empty), and main() exits 1 BEFORE
// generateDigest() when any is missing. A bare stub would make this whole
// suite unfalsifiable — it would fail for the wrong reason.
// ---------------------------------------------------------------------------
function adrDoc(fields) {
  const lines = [
    `# ADR-${fields.id} — ${fields.title}`,
    '',
    `**Status:** ${fields.status}`,
    `**Date:** ${fields.date}`,
    `**Slice:** ${fields.slice}`,
    '**Supersedes:** —',
    '**Amends:** —',
    `**Subsystems:** ${fields.subsystems}`,
    `**Decision:** ${fields.decision}`,
  ];
  // Status: Superseded additionally needs a REAL in-directory Superseded-by
  // target, or adr-digest.mjs:260-265 errors and we never reach generation.
  if (typeof fields.supersededBy === 'string') {
    lines.push(`**Superseded-by:** ${fields.supersededBy}`);
  }
  lines.push('', '## Context', '', 'Synthetic fixture written by scripts/adr-digest.test.mjs.', '');
  return lines.join('\n');
}

/**
 * Declare one fixture ADR. `file` defaults to the canonical NNNN-slug.md shape;
 * X4 overrides it to plant an out-of-band filename whose slice(0,4) id is still
 * collected by collectAdrIds' /^[0-9]{4}.*\.md$/ filter.
 */
function adr(id, options = {}) {
  const fields = {
    id,
    title: options.title ?? `Synthetic fixture ${id}`,
    status: options.status ?? 'Accepted',
    date: options.date ?? '2026-07-13',
    slice: options.slice ?? 'rb-43',
    subsystems: options.subsystems ?? 'tooling-docs',
    decision: options.decision ?? `Synthetic decision text for fixture ${id}; short and valid.`,
    supersededBy: options.supersededBy,
  };
  return { file: options.file ?? `${id}-synthetic-fixture.md`, content: adrDoc(fields) };
}

/** Materialise a corpus in a fresh mkdtemp dir and hand it to `fn`. */
function withCorpus(entries, fn) {
  const dir = mkdtempSync(join(tmpdir(), 'adr-digest-corpus-'));
  try {
    for (const entry of entries) {
      writeFileSync(join(dir, entry.file), entry.content, 'utf8');
    }
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Generate into a throwaway out dir; return the run plus the generated bytes. */
function generateFrom(adrDir) {
  const outDir = mkdtempSync(join(tmpdir(), 'adr-digest-out-'));
  try {
    const out = join(outDir, 'DIGEST.md');
    const run = runDigest(['--adr-dir', adrDir, '--out', out]);
    return { ...run, content: existsSync(out) ? readFileSync(out, 'utf8') : '' };
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Expected-line construction and extraction (String methods only)
// ---------------------------------------------------------------------------

/** The one true template. `highestId === null` renders the empty-corpus form. */
function expectedNextFreeLine(nextId, highestId) {
  const opening =
    highestId === null
      ? `${MARKER} **\`${nextId}\`** — no project ADRs on disk.`
      : `${MARKER} **\`${nextId}\`** — the highest id on disk (\`${highestId}\`) plus one. ` +
        'Gaps below it are never reused (`0002`–`0034` belong to the harness spec corpus).';
  return (
    `${opening} Regenerated by \`just adr-digest\` and drift-gated by \`just ci\`; it is a ` +
    'measurement, not a reservation — when a number is reserved for an in-flight slice the ' +
    'supervisor ledger is ahead of this line and is authoritative.'
  );
}

/** The trimmed marker line, or null when the generator renders none. */
function nextFreeLine(content) {
  for (const line of content.split('\n')) {
    if (line.trim().startsWith(MARKER)) return line.trim();
  }
  return null;
}

/**
 * The id inside the BOLD-CODE token, anchored on `**\`` … `\`**` rather than on
 * the first backtick pair: a future reword that adds an earlier inline-code
 * token would otherwise make X5 silently compare something else.
 */
function nextFreeIdFrom(line) {
  if (line === null) return null;
  const open = line.indexOf('**`');
  if (open === -1) return null;
  const close = line.indexOf('`**', open + 3);
  if (close === -1) return null;
  return line.slice(open + 3, close);
}

function countOccurrences(haystack, needle) {
  let count = 0;
  let idx = haystack.indexOf(needle);
  while (idx !== -1) {
    count++;
    idx = haystack.indexOf(needle, idx + needle.length);
  }
  return count;
}

// ---------------------------------------------------------------------------
// X6's LOCAL predicates. All three are positive-controlled inside X6 before
// they are pointed at the real README, so a red there is a finding and not a
// broken matcher.
// ---------------------------------------------------------------------------
function splitParagraphs(text) {
  const paragraphs = [];
  let current = [];
  for (const line of text.split('\n')) {
    if (line.trim() === '') {
      if (current.length > 0) {
        paragraphs.push(current.join('\n'));
        current = [];
      }
    } else {
      current.push(line);
    }
  }
  if (current.length > 0) paragraphs.push(current.join('\n'));
  return paragraphs;
}

/**
 * Fold every spelling of the phrase together: lowercase, then collapse runs of
 * whitespace, underscores and hyphens to one space. This is what makes
 * `next-free`, `next_free`, `.adr_next_free` and an ordinary hard wrap
 * (`the next\nfree number`) all match the single needle `next free` — a
 * three-spelling includes() test was measured to miss the wrapped shape.
 */
function normalizeForPhrase(text) {
  return text.toLowerCase().replace(/[\s_-]+/g, ' ');
}

function mentionsNextFree(paragraph) {
  return normalizeForPhrase(paragraph).includes('next free');
}

/** Paragraphs that both mention a next-free number AND carry a 4-digit run. */
function staleNextFreeParagraphs(text) {
  const violations = [];
  for (const paragraph of splitParagraphs(text)) {
    if (!mentionsNextFree(paragraph)) continue;
    if (/[0-9]{4}/.test(paragraph)) violations.push(paragraph);
  }
  return violations;
}

/**
 * Paragraphs that mention next-free AND name DIGEST.md — the "moved, not
 * deleted" predicate. Deleting the clause outright satisfies the stale-digit
 * check vacuously and would leave ADR-0060's "see docs/adr/README.md for the
 * current next-free number" pointing at nothing.
 */
function nextFreeParagraphsNamingDigest(text) {
  return splitParagraphs(text).filter((p) => mentionsNextFree(p) && p.includes('DIGEST.md'));
}

/**
 * Phrase-INDEPENDENT census: four-digit runs >= 0100 that survive stripping the
 * legitimate citation forms (an `ADR-NNNN` reference, a `(./NNNN-...)` link
 * target, a `[NNNN]` link label, a bare `NNNN-slug.md` path). A reworded
 * "Start your new ADR at **`0236`**" carries no next-free phrase at all and is
 * invisible to the two paragraph predicates; this one still sees the digit.
 * The >= 0100 floor is what lets README keep citing the harness block and the
 * collision note.
 */
function loudDigitsOutsideCitations(text) {
  const stripped = text
    .replace(/\(\.\/[0-9]{4}[^)]*\)/g, ' ')
    .replace(/\[[0-9]{4}[\]]/g, ' ')
    .replace(/ADR-[0-9]{4}/g, ' ')
    .replace(/[0-9]{4}-[a-z0-9-]*\.md/g, ' ');
  const found = new Set();
  for (const match of stripped.matchAll(/[0-9]{4}/g)) {
    if (Number(match[0]) >= 100) found.add(match[0]);
  }
  return [...found].sort();
}

// ===========================================================================
// X1 — derivation.
//
// KILLS: (a) a hardcoded/echoed constant (six corpora, six different answers);
// (b) a manual zero-prepend instead of padStart(4, '0') — the {0007, 0042}
// corpus renders `043` under `'0' + String(43)` and this asserts `0043`;
// (c) a filter to Status: Accepted before taking the max — the superseded-top
// and deprecated-top corpora would then render 0301 / 0513 instead of 0451 /
// 0778; (d) Math.max(...[]) on an EMPTY corpus, which is -Infinity and renders
// `-Infinity`/`NaN`/`aN` rather than the swapped `— no project ADRs on disk.`
// clause; (e) a count-based derivation (`adrs.length + 1`), which the gapped
// corpus renders as 0004; (f) an empty-corpus branch that keeps the non-empty
// wording (the whole first clause differs, not just a parenthetical).
// ===========================================================================
test('X1 derives the next free number as max+1, zero-padded, across six corpora', () => {
  const cases = [
    {
      label: 'gapped 0100/0180/0235',
      entries: [
        adr('0100', { subsystems: 'ci-gates' }),
        adr('0180', { subsystems: 'tooling-docs, ci-gates' }),
        adr('0235', { subsystems: 'schema-persistence' }),
      ],
      next: '0236',
      highest: '0235',
    },
    {
      label: 'low + padding-sensitive 0007/0042',
      entries: [
        adr('0007', { subsystems: 'battle', slice: 'm1' }),
        adr('0042', { subsystems: 'content', slice: 'm7b' }),
      ],
      next: '0043',
      highest: '0042',
    },
    {
      label: 'highest is Superseded',
      entries: [
        adr('0300', { subsystems: 'client-ui' }),
        adr('0450', {
          status: 'Superseded',
          supersededBy: 'ADR-0300',
          subsystems: 'client-ui, ci-gates',
        }),
      ],
      next: '0451',
      highest: '0450',
    },
    {
      label: 'highest is Deprecated',
      entries: [
        adr('0512', { subsystems: 'economy-quests' }),
        adr('0777', { status: 'Deprecated', subsystems: 'movement-netcode' }),
      ],
      next: '0778',
      highest: '0777',
    },
    {
      label: 'single ADR 0235',
      entries: [adr('0235', { subsystems: 'security-authz' })],
      next: '0236',
      highest: '0235',
    },
    {
      label: 'empty corpus',
      entries: [],
      next: '0001',
      highest: null,
    },
  ];

  const observed = cases.map((testCase) =>
    withCorpus(testCase.entries, (dir) => {
      const run = generateFrom(dir);
      return {
        label: testCase.label,
        code: run.code,
        line: nextFreeLine(run.content),
      };
    }),
  );
  const expected = cases.map((testCase) => ({
    label: testCase.label,
    code: 0,
    line: expectedNextFreeLine(testCase.next, testCase.highest),
  }));

  assert.deepEqual(
    observed,
    expected,
    'X1: every corpus must generate cleanly and render the derived next-free line verbatim',
  );
});

// ===========================================================================
// X2 — exact line, exact position, and sole ownership of the number.
//
// KILLS five measured cheats that all satisfy a bare `content.includes(...)`:
// (a) rendering inside an HTML comment (`<!-- Next free ... -->`) — the trim()
// EQUALITY rejects the `<!--` prefix; (b) rendering at end-of-file — the
// position assertions reject it; (c) INDENTING the line by four spaces, which
// markdown renders as a code block and which a trim()-only comparison accepts
// — the raw column-0 equality rejects it; (d) opening an unbalanced `<!--`
// earlier in the header region so the whole block (line included) is invisible
// while every structural assertion still holds — the balanced-comment count
// rejects it; (e) leaving a SECOND, contradictory hand-maintained number
// elsewhere in the digest — the sole-bold-code-token count rejects it. The
// bold-code shape `**\`` occurs nowhere else in a generated digest: the ADR
// table, the H- table and both notes use neither bold nor code there.
// ===========================================================================
test('X2 renders the line exactly once, verbatim, right after the Generated from line', () => {
  const entries = [
    adr('0120', { subsystems: 'tooling-docs' }),
    adr('0130', { subsystems: 'ci-gates, tooling-docs' }),
  ];
  withCorpus(entries, (dir) => {
    const run = generateFrom(dir);
    assert.equal(run.code, 0, `X2: generation should exit 0 but exited ${run.code}. ${run.stderr}`);

    const expected = expectedNextFreeLine('0131', '0130');
    const lines = run.content.split('\n');

    assert.equal(
      countOccurrences(run.content, MARKER),
      1,
      'X2: the next-free marker must appear EXACTLY ONCE in the generated digest',
    );

    const exactMatches = lines.filter((line) => line.trim() === expected).length;
    assert.equal(
      exactMatches,
      1,
      'X2: exactly one line must EQUAL the contract template verbatim (an HTML-comment ' +
        'wrapper or any reworded prose fails this equality while passing a substring test)',
    );

    const generatedIdx = lines.findIndex((line) => line.startsWith('Generated from '));
    assert.notEqual(generatedIdx, -1, 'X2: the digest must still carry the `Generated from ` line');

    let cursor = generatedIdx + 1;
    while (cursor < lines.length && lines[cursor].trim() === '') cursor++;
    assert.equal(
      lines[cursor] === undefined ? null : lines[cursor].trim(),
      expected,
      'X2: the next-free line must be the FIRST non-empty line after the `Generated from ` ' +
        'line (an end-of-file render passes a substring test and fails here)',
    );
    assert.equal(
      cursor,
      generatedIdx + 2,
      'X2: exactly one blank line must separate the `Generated from ` line from the next-free line',
    );

    // Leg: RAW equality at column 0 — a four-space indent renders as a code
    // block and is invisible as prose, but survives every trim()-based check.
    assert.equal(
      lines[cursor] === undefined ? null : lines[cursor],
      expected,
      'X2: the line must start at column 0 — an indented copy renders as a code block',
    );

    // Leg: the header region must not sit inside an unclosed HTML comment.
    const header = lines.slice(0, cursor + 1).join('\n');
    assert.equal(
      countOccurrences(header, '<!--'),
      countOccurrences(header, '-->'),
      'X2: HTML comment openers and closers must balance above the next-free line — an ' +
        'unbalanced `<!--` hides the whole header region from a reader while every ' +
        'structural assertion above still holds',
    );

    // Leg: exactly one bold-code number in the whole generated digest.
    assert.equal(
      countOccurrences(run.content, '**`'),
      1,
      'X2: the digest must carry exactly ONE bold-code number — a second, contradictory ' +
        'hand-maintained one elsewhere in the file is the bug this slice exists to remove',
    );
  });
});

// ===========================================================================
// X3 — reachability: the line is computed from the corpus AND lives inside the
// payload `--check` compares. FOUR and-ed legs, all measured before asserting.
//
// KILLS: (a) a constant line that does not move when the corpus grows;
// (c) a line spliced in at writeFileSync time — such an implementation makes a
// digest look stale against its own corpus; (d) the survivor of (c): a splice
// at write PLUS a matching strip of the line from `committed` before the
// compare, which passes legs (a)-(c) and is only caught by FORGING the value
// in the committed file and demanding that --check notices. Leg (b) alone
// proves nothing: today, with no feature at all, a bigger corpus already
// drifts on the table rows.
// ===========================================================================
test('X3 the derived line moves with the corpus and round-trips through --check', () => {
  const corpusA = [
    adr('0140', { subsystems: 'tooling-docs' }),
    adr('0205', { subsystems: 'ci-gates' }),
  ];
  const corpusB = [...corpusA, adr('0310', { subsystems: 'battle, content' })];

  const outDir = mkdtempSync(join(tmpdir(), 'adr-digest-x3-'));
  try {
    const digestA = join(outDir, 'DIGEST-A.md');

    const generateA = withCorpus(corpusA, (dirA) => {
      const run = runDigest(['--adr-dir', dirA, '--out', digestA]);
      return { code: run.code, stderr: run.stderr };
    });
    assert.equal(
      generateA.code,
      0,
      `X3: corpus A generation should exit 0. stderr: ${generateA.stderr.slice(0, 400)}`,
    );

    const lineA = nextFreeLine(readFileSync(digestA, 'utf8'));
    const lineB = withCorpus(corpusB, (dirB) => nextFreeLine(generateFrom(dirB).content));

    // Leg (b): A's digest is stale for corpus B.
    const checkB = withCorpus(corpusB, (dirB) =>
      runDigest(['--check', '--adr-dir', dirB, '--out', digestA]),
    );

    // Leg (c): A's digest is fresh for corpus A — the splice-at-write killer.
    const checkA = withCorpus(corpusA, (dirA) =>
      runDigest(['--check', '--adr-dir', dirA, '--out', digestA]),
    );

    // Leg (d): forge ONLY the id inside the bold-code token of the committed
    // digest and re-check. This asserts payload membership directly instead of
    // inferring it from a clean round-trip.
    const committed = readFileSync(digestA, 'utf8');
    const open = committed.indexOf('**`');
    const close = open === -1 ? -1 : committed.indexOf('`**', open + 3);
    let forgedCheck = 'not-attempted (no bold-code token in the generated digest)';
    if (open !== -1 && close !== -1) {
      writeFileSync(
        digestA,
        `${committed.slice(0, open + 3)}0184${committed.slice(close)}`,
        'utf8',
      );
      const run = withCorpus(corpusA, (dirA) =>
        runDigest(['--check', '--adr-dir', dirA, '--out', digestA]),
      );
      forgedCheck = run.code === 0 ? 'zero' : 'non-zero';
    }

    assert.deepEqual(
      {
        lineA,
        lineB,
        linesDiffer: lineA !== lineB,
        checkStaleCorpus: checkB.code === 0 ? 'zero' : 'non-zero',
        checkOwnCorpus: checkA.code === 0 ? 'zero' : 'non-zero',
        checkForgedNumber: forgedCheck,
      },
      {
        lineA: expectedNextFreeLine('0206', '0205'),
        lineB: expectedNextFreeLine('0311', '0310'),
        linesDiffer: true,
        checkStaleCorpus: 'non-zero',
        checkOwnCorpus: 'zero',
        checkForgedNumber: 'non-zero',
      },
      'X3: checkOwnCorpus must be zero (a splice at write time makes a digest stale against ' +
        'its own corpus) AND checkForgedNumber must be non-zero (a splice plus a matching ' +
        `strip before the compare passes every other leg). stderr(own): ${checkA.stderr.slice(0, 300)}`,
    );
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
});

// ===========================================================================
// X4 — band guard, in BOTH modes, on BOTH bounds, BEFORE any write.
//
// collectAdrIds' loose /^[0-9]{4}.*\.md$/ + slice(0,4) collects a date-named
// `2026-07-13-retro.md` as id 2026 and `10000-big.md` as id 1000, so a bare
// max+1 derivation is poisonable by dropping one file into docs/adr/.
//
// KILLS: (a) a guard behind `if (!checkMode)` — `just ci` only ever runs
// --check, so that is the half that matters, and the check-mode scenario below
// demands the BAND message rather than merely a non-zero exit (a missing --out
// already exits 1 for an unrelated reason); (b) a guard that validates only the
// DERIVED number instead of every collected id — the `0000-zero.md` scenario
// derives an in-band 0101 while carrying an out-of-band id; (c) a guard placed
// AFTER writeFileSync, which has already clobbered the target — the sentinel
// must survive byte-for-byte.
// ===========================================================================
test('X4 fails loud when a collected id falls outside the project band', () => {
  const scenarios = [
    {
      label: 'generate: date-named file collected as id 2026',
      check: false,
      entries: [
        adr('0100', { subsystems: 'tooling-docs' }),
        adr('2026', { file: '2026-07-13-retro.md', subsystems: 'tooling-docs' }),
      ],
    },
    {
      label: 'generate: five-digit file collected as id 1000',
      check: false,
      entries: [
        adr('0100', { subsystems: 'tooling-docs' }),
        adr('1000', { file: '10000-big.md', subsystems: 'ci-gates' }),
      ],
    },
    {
      label: 'generate: below-band id 0000 while the max stays in band',
      check: false,
      entries: [
        adr('0000', { file: '0000-zero.md', subsystems: 'tooling-docs' }),
        adr('0100', { subsystems: 'ci-gates' }),
      ],
    },
    {
      label: 'check: date-named file collected as id 2026',
      check: true,
      entries: [
        adr('0100', { subsystems: 'tooling-docs' }),
        adr('2026', { file: '2026-07-13-retro.md', subsystems: 'tooling-docs' }),
      ],
    },
  ];

  const observed = scenarios.map((scenario) =>
    withCorpus(scenario.entries, (dir) => {
      const outDir = mkdtempSync(join(tmpdir(), 'adr-digest-band-'));
      try {
        const out = join(outDir, 'DIGEST.md');
        writeFileSync(out, SENTINEL, 'utf8');
        const base = ['--adr-dir', dir, '--out', out];
        const run = runDigest(scenario.check ? ['--check', ...base] : base);
        return {
          label: scenario.label,
          exitNonZero: run.code !== 0,
          stderrNamesBand: run.stderr.includes(BAND_MESSAGE),
          outUnchanged: readFileSync(out, 'utf8') === SENTINEL,
        };
      } finally {
        rmSync(outDir, { recursive: true, force: true });
      }
    }),
  );
  const expected = scenarios.map((scenario) => ({
    label: scenario.label,
    exitNonZero: true,
    stderrNamesBand: true,
    outUnchanged: true,
  }));

  assert.deepEqual(
    observed,
    expected,
    `X4: every out-of-band corpus must exit non-zero naming "${BAND_MESSAGE}" on stderr, in ` +
      'generate AND check mode, without having written the --out target first',
  );
});

// ===========================================================================
// X5 — the live corpus, recomputed INDEPENDENTLY.
//
// Pure read of the COMMITTED digest; no spawn touches the real paths. The
// recompute deliberately uses a STRICTER rule than the implementation
// (`^[0-9]{4}-` — four digits then a hyphen) and additionally requires the
// answer to be inside the project band. Re-implementing collectAdrIds' looser
// filter would make this a tautology that agrees with a poisoned namespace, and
// hardcoding the number would reproduce README's hand-maintained bug one layer
// down.
//
// KILLS: a generator that renders the line only for synthetic fixtures (or
// renders it but is never re-run over the real corpus), and a committed digest
// that has drifted from the files on disk.
// ===========================================================================
test('X5 the committed digest agrees with an independent strict recompute', () => {
  let highest = 0;
  for (const file of readdirSync(REAL_ADR_DIR)) {
    if (!file.endsWith('.md')) continue;
    if (!/^[0-9]{4}-/.test(file)) continue;
    const value = Number(file.slice(0, 4));
    if (!Number.isInteger(value)) continue;
    if (value > highest) highest = value;
  }
  assert.equal(
    highest > 0,
    true,
    'X5: the strict recompute found no NNNN- named ADR in docs/adr/ — the fixture is vacuous',
  );

  const recomputed = highest + 1;
  assert.equal(
    recomputed < 1000,
    true,
    `X5: the recomputed next free number is ${recomputed}, outside the project band; the ` +
      'docs/adr/ namespace has been poisoned by an out-of-band file name',
  );
  const expectedId = String(recomputed).padStart(4, '0');

  const committed = readFileSync(join(REAL_ADR_DIR, 'DIGEST.md'), 'utf8');
  const line = nextFreeLine(committed);
  assert.notEqual(
    line,
    null,
    'X5: the committed docs/adr/DIGEST.md carries no next-free line — regenerate it with ' +
      '`just adr-digest` once the generator derives one',
  );
  assert.equal(
    nextFreeIdFrom(line),
    expectedId,
    `X5: the committed digest must name ${expectedId}, independently recomputed from ` +
      'the file names in docs/adr/',
  );
});

// ===========================================================================
// X6 — README hand-maintains no ADR number, and the clause MOVED rather than
// vanished. Three predicates, each positive-controlled first:
//
//   staleNextFreeParagraphs   — a next-free paragraph carrying a 4-digit run.
//   nextFreeParagraphsNamingDigest — exactly one paragraph must both mention
//                               next-free and name DIGEST.md.
//   loudDigitsOutsideCitations — phrase-independent: any 4-digit run >= 0100
//                               that is not a citation.
//
// Paragraph scope is mandatory in BOTH directions: line scope would false-RED
// the intended replacement (README's resolution rule shares a hard-wrapped line
// with the clause) and false-GREEN the wrapped/tabulated shapes below.
//
// KILLS four measured cheats: (a) leaving README untouched (today's state);
// (b) rewording so the digit survives without the phrase ("Start your new ADR
// at **`0236`**") — caught by the digit census; (c) renaming the phrase
// ("Next available number") — caught by the same census; (d) DELETING the
// clause entirely, which zeroes the stale count vacuously and orphans
// docs/adr/0060-evolution-fusion-content-shape.md:22 ("see docs/adr/README.md
// for the current next-free number") — caught by the moved-not-deleted leg.
// ===========================================================================
test('X6 README states no hand-maintained next-free number and still names DIGEST.md', () => {
  const controls = [
    {
      label: 'stale (i): digit on the same line as the phrase',
      text: [
        'Resolving a reference: an ADR numbered in the harness range goes to the spec corpus.',
        'Next free number: **`0184`**.',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'stale (ii): digit hard-wrapped onto the next line of the paragraph',
      text: [
        'Resolving a reference: the next free number for this directory is currently',
        '**`0184`**, so use that for your new ADR.',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'stale (iii): digit in a table row directly below the phrase',
      text: [
        'The next-free number is tracked in the table below:',
        '| Field | Value |',
        '|-------|-------|',
        '| next free | `0184` |',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'stale (iv): the PHRASE itself hard-wrapped across two lines',
      text: [
        'The catalog is generated, so the only hand-kept value left here is the next',
        'free number, currently **`0184`** for this directory.',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'cheat (v): reworded so the digit survives without the phrase',
      text: 'Start your new implementation ADR at **`0236`** (see [`DIGEST.md`](./DIGEST.md)).',
      stale: 0,
      namesDigest: 0,
      loudDigits: ['0236'],
    },
    {
      label: 'cheat (vi): the phrase renamed to "next available"',
      text: 'Next available number: **`0236`** — see [`DIGEST.md`](./DIGEST.md) for the catalog.',
      stale: 0,
      namesDigest: 0,
      loudDigits: ['0236'],
    },
    {
      label: 'clean: the replacement text the specialist is aiming at',
      text: [
        'The next free number is not written here. It is derived at generation time and',
        'rendered into [`DIGEST.md`](./DIGEST.md) by `just adr-digest`; when a number is',
        'reserved for an in-flight slice, the supervisor `mr-state.json` `.adr_next_free`',
        'field is ahead of that line and is authoritative.',
      ].join('\n'),
      stale: 0,
      namesDigest: 1,
      loudDigits: [],
    },
    {
      label: 'clean: ordinary citations must never be reported',
      text: [
        'See ADR-0104 and [0104](./0104-m-infra-d-adr-digest.md) for the generator, or',
        'read `docs/adr/0104-m-infra-d-adr-digest.md` directly.',
      ].join('\n'),
      stale: 0,
      namesDigest: 0,
      loudDigits: [],
    },
  ];

  const controlObserved = controls.map((control) => ({
    label: control.label,
    stale: staleNextFreeParagraphs(control.text).length,
    namesDigest: nextFreeParagraphsNamingDigest(control.text).length,
    loudDigits: loudDigitsOutsideCitations(control.text),
  }));
  const controlExpected = controls.map((control) => ({
    label: control.label,
    stale: control.stale,
    namesDigest: control.namesDigest,
    loudDigits: control.loudDigits,
  }));
  assert.deepEqual(
    controlObserved,
    controlExpected,
    'X6: the three local predicates must report every stale shape and no clean one — if this ' +
      'fails, the matcher is broken and the live verdict below means nothing',
  );

  // --- The real file.
  const readme = readFileSync(join(REAL_ADR_DIR, 'README.md'), 'utf8');
  const stale = staleNextFreeParagraphs(readme);
  assert.deepEqual(
    {
      staleParagraphs: stale.length,
      paragraphsNamingDigest: nextFreeParagraphsNamingDigest(readme).length,
      loudDigits: loudDigitsOutsideCitations(readme),
      mentionsDigestFile: readme.includes('DIGEST.md'),
    },
    {
      staleParagraphs: 0,
      paragraphsNamingDigest: 1,
      loudDigits: [],
      mentionsDigestFile: true,
    },
    'X6: docs/adr/README.md must hand-maintain no ADR number (loudDigits empty), and exactly ' +
      'ONE paragraph must both mention the next-free number and name DIGEST.md — deleting ' +
      `the clause is not a fix. Offending paragraph(s):\n${stale.join('\n---\n')}`,
  );
});
