// scripts/adr-digest.test.mjs — rb-43 RED gate: the DERIVED "next free project
// ADR number" line that scripts/adr-digest.mjs must render into the generated
// docs/adr/DIGEST.md, replacing the hand-maintained digit in docs/adr/README.md.
//
// WHAT IS GATED (the frozen contract):
//   1. The rendered line, exact template. Non-empty corpus: NNNN = highest id on
//      disk plus one, MMMM = that highest id. EMPTY corpus: the WHOLE first
//      clause is swapped for `— no project ADRs on disk.` (not just a
//      parenthetical — `(highest on disk: none) plus one` is not English).
//      The line claims only checkable things: it is regenerated by
//      `just adr-digest` and drift-gated by `just ci`. It does NOT claim to be
//      "never hand-maintained" — that is unverifiable provenance.
//   2. Position: first non-empty line after the `Generated from ...` line,
//      separated by exactly one blank line, at column 0, outside any HTML
//      comment, and the ONLY bold-code number in the generated digest.
//   3. Band guard: any COLLECTED id outside 0001-0999 fails loud — in generate
//      AND in --check mode, before any write, naming the band on stderr.
//   4. The CLI is otherwise unchanged (--adr-dir / --out / --check), and the
//      derived line lives INSIDE the payload --check compares.
//   5. docs/adr/README.md hand-maintains no ADR number at all, and its
//      next-free paragraph still points at DIGEST.md (moved, not deleted).
//
// RED CHECKPOINT — recorded history, NOT a live claim. At commit d1edade
// (2026-09-04), before the implementation landed, scripts/adr-digest.mjs
// rendered no such line and had no band guard, and docs/adr/README.md still
// carried a hand-maintained four-digit number in its "Resolving a reference"
// paragraph; all six tests failed there, each for its own reason. The generator
// now ships the feature and this suite is green — do not read the paragraph
// above as a description of the current tree, and do not chase README:16.
//
// ---------------------------------------------------------------------------
// rb-70 EXTENSION — X7 and X8 gate a SECOND, unrelated contract: the
// `**Extends:**` / `**Extended-by:**` relation pair, which adr-digest modelled
// nowhere before this slice.
//
//   6. Dangling-reference checks cover **Extends:** and **Extended-by:** the
//      same way they already cover Amends/Supersedes — and BOTH fields stay
//      OPTIONAL. Their absence is never an error (193 real ADRs declare
//      neither; a "required field" reading reds the whole corpus).
//   7. REVERSE reciprocity, corpus-wide: for every ADR Y and every X named by
//      Y's **Extended-by:**, X must name Y in its **Extends:**. Corpus-wide
//      means corpus-wide — no era window, no tolerance set, no size cutoff, in
//      generate mode AND in --check mode, at ERROR level (non-zero exit), with
//      no new WARN line. Relations are read off the fence-stripped,
//      preamble-bounded back-link view, so a fenced, indented or below-the-
//      first-heading spelling is NOT a declaration.
//   8. FORWARD reciprocity (**Extends:** ⇒ **Extended-by:**) is deliberately
//      NOT enforced: the live corpus carries ~44 one-directional edges whose
//      repair is a semantic claim, and rb-70 DEFERred it as wontfix. No test
//      here demands it, and the fixtures are built so that adding it would not
//      be needed to pass — see the note on X7's G3 arms.
//   9. Six REAL corpus edges are frozen by roster in X8, on BOTH legs. This is
//      the only tooth on "delete an **Extended-by:** line from a real ADR" —
//      rule 7 cannot see that deletion, because deleting the line deletes the
//      premise of the reverse rule.
//
// X7 emits a `RB70-Gn:OK` marker on stdout at the end of each clause group and
// X8 emits one at its end. Each is printed AFTER that group's assertion, so an
// absent marker means that group did not pass. They are the acceptance-ledger
// EXPECT strings: each `RB70-...:OK` literal occurs exactly once in this file
// and appears in no failure message.
//
// SUITE SIZE — `justfile`'s adr-digest recipe asserts the passing-test count by
// EQUALITY. This file is now an EIGHT-test contract; that number and this
// sentence move together or not at all.
// ---------------------------------------------------------------------------
//
// SAFETY — every spawn passes BOTH --adr-dir AND --out into a mkdtemp dir, and
// `--adr-dir` IS THE LOAD-BEARING ONE: scripts/adr-digest.mjs declares its
// output path in the `DIGEST_PATH` constant, and that constant falls back to a
// DIGEST.md inside `ADR_DIR` whenever `--out` is absent. (Cited by declaration
// rather than by line: it sat immediately below the CLI-argument block as of
// 2026-09-07, and that hint is a hint, not the contract.) So a run with
// --adr-dir but no --out writes into the temp corpus dir, while a run with
// --out but no --adr-dir READS the real corpus (and a check-mode run compares
// against it). Do not relax --adr-dir. Every temp dir is removed in a
// `finally`. X5, X6 and X8 only READ the real files; they never spawn.
//
// NEVER `import` scripts/adr-digest.mjs from this file: it calls main() at
// module scope, so an import would run the generator against the real corpus.
// Every predicate below is a local re-implementation on purpose.
//
// IMPORTANT: NO new RegExp(...) anywhere — the remote-only Semgrep rule
// detect-non-literal-regexp has bitten this project 3x. Literal /regex/ and
// String.includes/indexOf/startsWith only.
//
// X1/X4/X6 collect every fixture's outcome and assert ONCE on the collected
// array: `assert` throws on first failure, so a per-fixture assert would leave
// most of the corpora unmeasured on a red run.
//
// Runs as: node --test scripts/adr-digest.test.mjs   (from the repo root)

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SCRIPT = join(ROOT, 'scripts', 'adr-digest.mjs');
const REAL_ADR_DIR = join(ROOT, 'docs', 'adr');

/** The stable prefix of the derived line — the handle every assertion grabs. */
const MARKER = 'Next free project ADR number:';

/** Contract §3: the substring the band guard must print on stderr. */
const BAND_MESSAGE = 'outside the project ADR band 0001-0999';

/** Written into every band-guard run's --out target; must survive a loud failure. */
const SENTINEL = 'SENTINEL — a run that fails the band guard must not write this file.\n';

// ---------------------------------------------------------------------------
// Process helper — spawnSync so an exit code is data, not a throw. A spawn
// FAILURE (ENOENT, EMFILE) is folded into stderr so it can never be misread as
// a content failure.
// ---------------------------------------------------------------------------
function runDigest(args) {
  const result = spawnSync('node', [SCRIPT, ...args], {
    cwd: ROOT,
    encoding: 'utf8',
    stdio: 'pipe',
  });
  const spawnError = result.error ? `\n[spawn error] ${result.error.message}` : '';
  return {
    code: result.status !== null ? result.status : 1,
    stderr: `${result.stderr ?? ''}${spawnError}`,
    stdout: result.stdout ?? '',
  };
}

// ---------------------------------------------------------------------------
// Fixture builder — canonical header shape, copied from
// evals/fixtures/adr-digest/0900-good.md and checked against validateAdr():
// Status, Date, Slice, Supersedes, Amends, Subsystems, Decision are all
// required (LEGACY_TOLERANCE is empty), and main() exits 1 BEFORE
// generateDigest() when any is missing. A bare stub would make this whole
// suite unfalsifiable — it would fail for the wrong reason.
// ---------------------------------------------------------------------------
function adrDoc(fields) {
  const lines = [
    `# ADR-${fields.id} — ${fields.title}`,
    '',
    `**Status:** ${fields.status}`,
    `**Date:** ${fields.date}`,
    `**Slice:** ${fields.slice}`,
    '**Supersedes:** —',
    '**Amends:** —',
    `**Subsystems:** ${fields.subsystems}`,
    `**Decision:** ${fields.decision}`,
  ];
  // Status: Superseded additionally needs a REAL in-directory Superseded-by
  // target, or validateAdr() in scripts/adr-digest.mjs raises its "Status is
  // Superseded but missing a real ... pointer" error and we never reach
  // generation. (Cited by declaration, not by line: that check sat in the low
  // 260s on 2026-09-07 and is expected to drift.)
  if (typeof fields.supersededBy === 'string') {
    lines.push(`**Superseded-by:** ${fields.supersededBy}`);
  }
  // rb-70 passthroughs. Both are OMITTED unless asked for — that default IS the
  // "the fields are optional" fixture, and it is what keeps X1-X4 byte-identical.
  // Position within the preamble is irrelevant to both readers (the bold-field
  // reader indexes the preamble; the back-link reader scans preamble lines), so
  // appending here rather than beside **Amends:** costs nothing.
  if (typeof fields.extends === 'string') {
    lines.push(`**Extends:** ${fields.extends}`);
  }
  if (typeof fields.extendedBy === 'string') {
    lines.push(`**Extended-by:** ${fields.extendedBy}`);
  }
  // Raw lines appended to the END of the preamble (X7/G4 plants a fenced or an
  // indented relation line here) and to the END of the body (X7/G4 plants a
  // column-0 relation line BELOW the first `## ` heading there).
  for (const raw of fields.extraPreamble ?? []) lines.push(raw);
  lines.push('', '## Context', '', 'Synthetic fixture written by scripts/adr-digest.test.mjs.', '');
  for (const raw of fields.extraBody ?? []) lines.push(raw);
  return lines.join('\n');
}

/**
 * Declare one fixture ADR. `file` defaults to the canonical NNNN-slug.md shape;
 * X4 overrides it to plant an out-of-band filename whose slice(0,4) id is still
 * collected by collectAdrIds' /^[0-9]{4}.*\.md$/ filter.
 */
function adr(id, options = {}) {
  const fields = {
    id,
    title: options.title ?? `Synthetic fixture ${id}`,
    status: options.status ?? 'Accepted',
    date: options.date ?? '2026-07-13',
    slice: options.slice ?? 'rb-43',
    subsystems: options.subsystems ?? 'tooling-docs',
    decision: options.decision ?? `Synthetic decision text for fixture ${id}; short and valid.`,
    supersededBy: options.supersededBy,
    extends: options.extends,
    extendedBy: options.extendedBy,
    extraPreamble: options.extraPreamble,
    extraBody: options.extraBody,
  };
  return { file: options.file ?? `${id}-synthetic-fixture.md`, content: adrDoc(fields) };
}

/** Materialise a corpus in a fresh mkdtemp dir and hand it to `fn`. */
function withCorpus(entries, fn) {
  const dir = mkdtempSync(join(tmpdir(), 'adr-digest-corpus-'));
  try {
    for (const entry of entries) {
      writeFileSync(join(dir, entry.file), entry.content, 'utf8');
    }
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Generate into a throwaway out dir; return the run plus the generated bytes. */
function generateFrom(adrDir) {
  const outDir = mkdtempSync(join(tmpdir(), 'adr-digest-out-'));
  try {
    const out = join(outDir, 'DIGEST.md');
    const run = runDigest(['--adr-dir', adrDir, '--out', out]);
    return { ...run, content: existsSync(out) ? readFileSync(out, 'utf8') : '' };
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Expected-line construction and extraction (String methods only)
// ---------------------------------------------------------------------------

/** The one true template. `highestId === null` renders the empty-corpus form. */
function expectedNextFreeLine(nextId, highestId) {
  const opening =
    highestId === null
      ? `${MARKER} **\`${nextId}\`** — no project ADRs on disk.`
      : `${MARKER} **\`${nextId}\`** — the highest id on disk (\`${highestId}\`) plus one. ` +
        'Gaps below it are never reused (`0002`–`0034` belong to the harness spec corpus).';
  return (
    `${opening} Regenerated by \`just adr-digest\` and drift-gated by \`just ci\`; it is a ` +
    'measurement, not a reservation — when a number is reserved for an in-flight slice the ' +
    'supervisor ledger is ahead of this line and is authoritative.'
  );
}

/** The trimmed marker line, or null when the generator renders none. */
function nextFreeLine(content) {
  for (const line of content.split('\n')) {
    if (line.trim().startsWith(MARKER)) return line.trim();
  }
  return null;
}

/**
 * The id inside the BOLD-CODE token, anchored on `**\`` … `\`**` rather than on
 * the first backtick pair: a future reword that adds an earlier inline-code
 * token would otherwise make X5 silently compare something else.
 */
function nextFreeIdFrom(line) {
  if (line === null) return null;
  const open = line.indexOf('**`');
  if (open === -1) return null;
  const close = line.indexOf('`**', open + 3);
  if (close === -1) return null;
  return line.slice(open + 3, close);
}

function countOccurrences(haystack, needle) {
  let count = 0;
  let idx = haystack.indexOf(needle);
  while (idx !== -1) {
    count++;
    idx = haystack.indexOf(needle, idx + needle.length);
  }
  return count;
}

// ---------------------------------------------------------------------------
// X6's LOCAL predicates. All three are positive-controlled inside X6 before
// they are pointed at the real README, so a red there is a finding and not a
// broken matcher.
// ---------------------------------------------------------------------------
function splitParagraphs(text) {
  const paragraphs = [];
  let current = [];
  for (const line of text.split('\n')) {
    if (line.trim() === '') {
      if (current.length > 0) {
        paragraphs.push(current.join('\n'));
        current = [];
      }
    } else {
      current.push(line);
    }
  }
  if (current.length > 0) paragraphs.push(current.join('\n'));
  return paragraphs;
}

/**
 * Fold every spelling of the phrase together: lowercase, then collapse runs of
 * whitespace, underscores and hyphens to one space. This is what makes
 * `next-free`, `next_free`, `.adr_next_free` and an ordinary hard wrap
 * (`the next\nfree number`) all match the single needle `next free` — a
 * three-spelling includes() test was measured to miss the wrapped shape.
 */
function normalizeForPhrase(text) {
  return text.toLowerCase().replace(/[\s_-]+/g, ' ');
}

function mentionsNextFree(paragraph) {
  return normalizeForPhrase(paragraph).includes('next free');
}

/** Paragraphs that both mention a next-free number AND carry a 4-digit run. */
function staleNextFreeParagraphs(text) {
  const violations = [];
  for (const paragraph of splitParagraphs(text)) {
    if (!mentionsNextFree(paragraph)) continue;
    if (/[0-9]{4}/.test(paragraph)) violations.push(paragraph);
  }
  return violations;
}

/**
 * Paragraphs that mention next-free AND name DIGEST.md — the "moved, not
 * deleted" predicate. Deleting the clause outright satisfies the stale-digit
 * check vacuously and would leave ADR-0060's "see docs/adr/README.md for the
 * current next-free number" pointing at nothing.
 */
function nextFreeParagraphsNamingDigest(text) {
  return splitParagraphs(text).filter((p) => mentionsNextFree(p) && p.includes('DIGEST.md'));
}

/**
 * Phrase-INDEPENDENT census: four-digit runs >= 0100 that survive stripping the
 * legitimate citation forms (an `ADR-NNNN` reference, a `(./NNNN-...)` link
 * target, a `[NNNN]` link label, a bare `NNNN-slug.md` path). A reworded
 * "Start your new ADR at **`0236`**" carries no next-free phrase at all and is
 * invisible to the two paragraph predicates; this one still sees the digit.
 * The >= 0100 floor is what lets README keep citing the harness block and the
 * collision note.
 *
 * A plausible YEAR (19xx/20xx) is not an ADR-number claim and is excluded:
 * "last restructured in 2026 by slice rb-43" is an innocent README edit, and
 * reporting it would red `just test` under a message about a hand-maintained
 * ADR number that is not there. Project ids stop at 0999, so no real next-free
 * number can hide behind this exclusion. Everything else stays as-is — this is
 * the leg that kills the "Next available number: **`0236`**" reword cheat.
 */
function loudDigitsOutsideCitations(text) {
  const stripped = text
    .replace(/\(\.\/[0-9]{4}[^)]*\)/g, ' ')
    .replace(/\[[0-9]{4}[\]]/g, ' ')
    .replace(/ADR-[0-9]{4}/g, ' ')
    .replace(/[0-9]{4}-[a-z0-9-]*\.md/g, ' ');
  const found = new Set();
  for (const match of stripped.matchAll(/[0-9]{4}/g)) {
    const token = match[0];
    if (/^(19|20)[0-9]{2}$/.test(token)) continue;
    if (Number(token) >= 100) found.add(token);
  }
  return [...found].sort();
}

// ===========================================================================
// X1 — derivation.
//
// KILLS: (a) a hardcoded/echoed constant (six corpora, six different answers);
// (b) a manual zero-prepend instead of padStart(4, '0') — the {0007, 0042}
// corpus renders `043` under `'0' + String(43)` and this asserts `0043`;
// (c) a filter to Status: Accepted before taking the max — the superseded-top
// and deprecated-top corpora would then render 0301 / 0513 instead of 0451 /
// 0778; (d) Math.max(...[]) on an EMPTY corpus, which is -Infinity and renders
// `-Infinity`/`NaN`/`aN` rather than the swapped `— no project ADRs on disk.`
// clause; (e) a count-based derivation (`adrs.length + 1`), which the gapped
// corpus renders as 0004; (f) an empty-corpus branch that keeps the non-empty
// wording (the whole first clause differs, not just a parenthetical).
// ===========================================================================
test('X1 derives the next free number as max+1, zero-padded, across six corpora', () => {
  const cases = [
    {
      label: 'gapped 0100/0180/0235',
      entries: [
        adr('0100', { subsystems: 'ci-gates' }),
        adr('0180', { subsystems: 'tooling-docs, ci-gates' }),
        adr('0235', { subsystems: 'schema-persistence' }),
      ],
      next: '0236',
      highest: '0235',
    },
    {
      label: 'low + padding-sensitive 0007/0042',
      entries: [
        adr('0007', { subsystems: 'battle', slice: 'm1' }),
        adr('0042', { subsystems: 'content', slice: 'm7b' }),
      ],
      next: '0043',
      highest: '0042',
    },
    {
      label: 'highest is Superseded',
      entries: [
        adr('0300', { subsystems: 'client-ui' }),
        adr('0450', {
          status: 'Superseded',
          supersededBy: 'ADR-0300',
          subsystems: 'client-ui, ci-gates',
        }),
      ],
      next: '0451',
      highest: '0450',
    },
    {
      label: 'highest is Deprecated',
      entries: [
        adr('0512', { subsystems: 'economy-quests' }),
        adr('0777', { status: 'Deprecated', subsystems: 'movement-netcode' }),
      ],
      next: '0778',
      highest: '0777',
    },
    {
      label: 'single ADR 0235',
      entries: [adr('0235', { subsystems: 'security-authz' })],
      next: '0236',
      highest: '0235',
    },
    {
      label: 'empty corpus',
      entries: [],
      next: '0001',
      highest: null,
    },
  ];

  const observed = cases.map((testCase) =>
    withCorpus(testCase.entries, (dir) => {
      const run = generateFrom(dir);
      return {
        label: testCase.label,
        code: run.code,
        line: nextFreeLine(run.content),
      };
    }),
  );
  const expected = cases.map((testCase) => ({
    label: testCase.label,
    code: 0,
    line: expectedNextFreeLine(testCase.next, testCase.highest),
  }));

  assert.deepEqual(
    observed,
    expected,
    'X1: every corpus must generate cleanly and render the derived next-free line verbatim',
  );
});

// ===========================================================================
// X2 — exact line, exact position, and sole ownership of the number.
//
// KILLS five measured cheats that all satisfy a bare `content.includes(...)`:
// (a) rendering inside an HTML comment (`<!-- Next free ... -->`) — the trim()
// EQUALITY rejects the `<!--` prefix; (b) rendering at end-of-file — the
// position assertions reject it; (c) INDENTING the line by four spaces, which
// markdown renders as a code block and which a trim()-only comparison accepts
// — the raw column-0 equality rejects it; (d) opening an unbalanced `<!--`
// earlier in the header region so the whole block (line included) is invisible
// while every structural assertion still holds — the balanced-comment count
// rejects it; (e) leaving a SECOND, contradictory hand-maintained number
// elsewhere in the digest — the sole-bold-code-token count rejects it. The
// bold-code shape `**\`` occurs nowhere else in a generated digest: the ADR
// table, the H- table and both notes use neither bold nor code there.
// ===========================================================================
test('X2 renders the line exactly once, verbatim, right after the Generated from line', () => {
  const entries = [
    adr('0120', { subsystems: 'tooling-docs' }),
    adr('0130', { subsystems: 'ci-gates, tooling-docs' }),
  ];
  withCorpus(entries, (dir) => {
    const run = generateFrom(dir);
    assert.equal(run.code, 0, `X2: generation should exit 0 but exited ${run.code}. ${run.stderr}`);

    const expected = expectedNextFreeLine('0131', '0130');
    const lines = run.content.split('\n');

    assert.equal(
      countOccurrences(run.content, MARKER),
      1,
      'X2: the next-free marker must appear EXACTLY ONCE in the generated digest',
    );

    const exactMatches = lines.filter((line) => line.trim() === expected).length;
    assert.equal(
      exactMatches,
      1,
      'X2: exactly one line must EQUAL the contract template verbatim (an HTML-comment ' +
        'wrapper or any reworded prose fails this equality while passing a substring test)',
    );

    const generatedIdx = lines.findIndex((line) => line.startsWith('Generated from '));
    assert.notEqual(generatedIdx, -1, 'X2: the digest must still carry the `Generated from ` line');

    let cursor = generatedIdx + 1;
    while (cursor < lines.length && lines[cursor].trim() === '') cursor++;
    assert.equal(
      lines[cursor] === undefined ? null : lines[cursor].trim(),
      expected,
      'X2: the next-free line must be the FIRST non-empty line after the `Generated from ` ' +
        'line (an end-of-file render passes a substring test and fails here)',
    );
    assert.equal(
      cursor,
      generatedIdx + 2,
      'X2: exactly one blank line must separate the `Generated from ` line from the next-free line',
    );

    // Leg: RAW equality at column 0 — a four-space indent renders as a code
    // block and is invisible as prose, but survives every trim()-based check.
    assert.equal(
      lines[cursor] === undefined ? null : lines[cursor],
      expected,
      'X2: the line must start at column 0 — an indented copy renders as a code block',
    );

    // Leg: the header region must not sit inside an unclosed HTML comment.
    const header = lines.slice(0, cursor + 1).join('\n');
    assert.equal(
      countOccurrences(header, '<!--'),
      countOccurrences(header, '-->'),
      'X2: HTML comment openers and closers must balance above the next-free line — an ' +
        'unbalanced `<!--` hides the whole header region from a reader while every ' +
        'structural assertion above still holds',
    );

    // Leg: exactly one bold-code number in the whole generated digest.
    assert.equal(
      countOccurrences(run.content, '**`'),
      1,
      'X2: the digest must carry exactly ONE bold-code number — a second, contradictory ' +
        'hand-maintained one elsewhere in the file is the bug this slice exists to remove',
    );
  });
});

// ===========================================================================
// X3 — reachability: the line is computed from the corpus AND lives inside the
// payload `--check` compares. FOUR and-ed legs, all measured before asserting.
//
// KILLS: (a) a constant line that does not move when the corpus grows;
// (c) a line spliced in at writeFileSync time — such an implementation makes a
// digest look stale against its own corpus; (d) the survivor of (c): a splice
// at write PLUS a matching strip of the line from `committed` before the
// compare, which passes legs (a)-(c) and is only caught by FORGING the value
// in the committed file and demanding that --check notices. Leg (b) alone
// proves nothing: today, with no feature at all, a bigger corpus already
// drifts on the table rows.
// ===========================================================================
test('X3 the derived line moves with the corpus and round-trips through --check', () => {
  const corpusA = [
    adr('0140', { subsystems: 'tooling-docs' }),
    adr('0205', { subsystems: 'ci-gates' }),
  ];
  const corpusB = [...corpusA, adr('0310', { subsystems: 'battle, content' })];

  const outDir = mkdtempSync(join(tmpdir(), 'adr-digest-x3-'));
  try {
    const digestA = join(outDir, 'DIGEST-A.md');

    const generateA = withCorpus(corpusA, (dirA) => {
      const run = runDigest(['--adr-dir', dirA, '--out', digestA]);
      return { code: run.code, stderr: run.stderr };
    });
    assert.equal(
      generateA.code,
      0,
      `X3: corpus A generation should exit 0. stderr: ${generateA.stderr.slice(0, 400)}`,
    );

    const lineA = nextFreeLine(readFileSync(digestA, 'utf8'));
    const lineB = withCorpus(corpusB, (dirB) => nextFreeLine(generateFrom(dirB).content));

    // Leg (b): A's digest is stale for corpus B.
    const checkB = withCorpus(corpusB, (dirB) =>
      runDigest(['--check', '--adr-dir', dirB, '--out', digestA]),
    );

    // Leg (c): A's digest is fresh for corpus A — the splice-at-write killer.
    const checkA = withCorpus(corpusA, (dirA) =>
      runDigest(['--check', '--adr-dir', dirA, '--out', digestA]),
    );

    // Leg (d): forge ONLY the id inside the bold-code token of the committed
    // digest and re-check. This asserts payload membership directly instead of
    // inferring it from a clean round-trip.
    const committed = readFileSync(digestA, 'utf8');
    const open = committed.indexOf('**`');
    const close = open === -1 ? -1 : committed.indexOf('`**', open + 3);
    let forgedCheck = 'not-attempted (no bold-code token in the generated digest)';
    if (open !== -1 && close !== -1) {
      writeFileSync(
        digestA,
        `${committed.slice(0, open + 3)}0184${committed.slice(close)}`,
        'utf8',
      );
      const run = withCorpus(corpusA, (dirA) =>
        runDigest(['--check', '--adr-dir', dirA, '--out', digestA]),
      );
      forgedCheck = run.code === 0 ? 'zero' : 'non-zero';
    }

    assert.deepEqual(
      {
        lineA,
        lineB,
        linesDiffer: lineA !== lineB,
        checkStaleCorpus: checkB.code === 0 ? 'zero' : 'non-zero',
        checkOwnCorpus: checkA.code === 0 ? 'zero' : 'non-zero',
        checkForgedNumber: forgedCheck,
      },
      {
        lineA: expectedNextFreeLine('0206', '0205'),
        lineB: expectedNextFreeLine('0311', '0310'),
        linesDiffer: true,
        checkStaleCorpus: 'non-zero',
        checkOwnCorpus: 'zero',
        checkForgedNumber: 'non-zero',
      },
      'X3: checkOwnCorpus must be zero (a splice at write time makes a digest stale against ' +
        'its own corpus) AND checkForgedNumber must be non-zero (a splice plus a matching ' +
        `strip before the compare passes every other leg). stderr(own): ${checkA.stderr.slice(0, 300)}`,
    );
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
});

// ===========================================================================
// X4 — band guard, in BOTH modes, on BOTH bounds, BEFORE any write.
//
// collectAdrIds' loose /^[0-9]{4}.*\.md$/ + slice(0,4) collects a date-named
// `2026-07-13-retro.md` as id 2026 and `10000-big.md` as id 1000, so a bare
// max+1 derivation is poisonable by dropping one file into docs/adr/.
//
// KILLS: (a) a guard behind `if (!checkMode)` — `just ci` only ever runs
// --check, so that is the half that matters, and the check-mode scenario below
// demands the BAND message rather than merely a non-zero exit (a missing --out
// already exits 1 for an unrelated reason); (b) a guard that validates only the
// DERIVED number instead of every collected id — the `0000-zero.md` scenario
// derives an in-band 0101 while carrying an out-of-band id; (c) a guard placed
// AFTER writeFileSync, which has already clobbered the target — the sentinel
// must survive byte-for-byte.
// ===========================================================================
test('X4 fails loud when a collected id falls outside the project band', () => {
  const scenarios = [
    {
      label: 'generate: date-named file collected as id 2026',
      check: false,
      entries: [
        adr('0100', { subsystems: 'tooling-docs' }),
        adr('2026', { file: '2026-07-13-retro.md', subsystems: 'tooling-docs' }),
      ],
    },
    {
      label: 'generate: five-digit file collected as id 1000',
      check: false,
      entries: [
        adr('0100', { subsystems: 'tooling-docs' }),
        adr('1000', { file: '10000-big.md', subsystems: 'ci-gates' }),
      ],
    },
    {
      label: 'generate: below-band id 0000 while the max stays in band',
      check: false,
      entries: [
        adr('0000', { file: '0000-zero.md', subsystems: 'tooling-docs' }),
        adr('0100', { subsystems: 'ci-gates' }),
      ],
    },
    {
      label: 'check: date-named file collected as id 2026',
      check: true,
      entries: [
        adr('0100', { subsystems: 'tooling-docs' }),
        adr('2026', { file: '2026-07-13-retro.md', subsystems: 'tooling-docs' }),
      ],
    },
  ];

  const observed = scenarios.map((scenario) =>
    withCorpus(scenario.entries, (dir) => {
      const outDir = mkdtempSync(join(tmpdir(), 'adr-digest-band-'));
      try {
        const out = join(outDir, 'DIGEST.md');
        writeFileSync(out, SENTINEL, 'utf8');
        const base = ['--adr-dir', dir, '--out', out];
        const run = runDigest(scenario.check ? ['--check', ...base] : base);
        return {
          label: scenario.label,
          exitNonZero: run.code !== 0,
          stderrNamesBand: run.stderr.includes(BAND_MESSAGE),
          outUnchanged: readFileSync(out, 'utf8') === SENTINEL,
        };
      } finally {
        rmSync(outDir, { recursive: true, force: true });
      }
    }),
  );
  const expected = scenarios.map((scenario) => ({
    label: scenario.label,
    exitNonZero: true,
    stderrNamesBand: true,
    outUnchanged: true,
  }));

  assert.deepEqual(
    observed,
    expected,
    `X4: every out-of-band corpus must exit non-zero naming "${BAND_MESSAGE}" on stderr, in ` +
      'generate AND check mode, without having written the --out target first',
  );
});

// ===========================================================================
// X5 — the live corpus, recomputed INDEPENDENTLY.
//
// Pure read of the COMMITTED digest; no spawn touches the real paths. The
// recompute deliberately uses a STRICTER rule than the implementation
// (`^[0-9]{4}-` — four digits then a hyphen) and additionally requires the
// answer to be inside the project band. Re-implementing collectAdrIds' looser
// filter would make this a tautology that agrees with a poisoned namespace, and
// hardcoding the number would reproduce README's hand-maintained bug one layer
// down.
//
// KILLS: a generator that renders the line only for synthetic fixtures (or
// renders it but is never re-run over the real corpus), and a committed digest
// that has drifted from the files on disk.
// ===========================================================================
test('X5 the committed digest agrees with an independent strict recompute', () => {
  let highest = 0;
  for (const file of readdirSync(REAL_ADR_DIR)) {
    if (!file.endsWith('.md')) continue;
    if (!/^[0-9]{4}-/.test(file)) continue;
    const value = Number(file.slice(0, 4));
    if (!Number.isInteger(value)) continue;
    if (value > highest) highest = value;
  }
  assert.equal(
    highest > 0,
    true,
    'X5: the strict recompute found no NNNN- named ADR in docs/adr/ — the fixture is vacuous',
  );

  const recomputed = highest + 1;
  assert.equal(
    recomputed < 1000,
    true,
    `X5: the recomputed next free number is ${recomputed}, outside the project band; the ` +
      'docs/adr/ namespace has been poisoned by an out-of-band file name',
  );
  const expectedId = String(recomputed).padStart(4, '0');

  const committed = readFileSync(join(REAL_ADR_DIR, 'DIGEST.md'), 'utf8');
  const line = nextFreeLine(committed);
  assert.notEqual(
    line,
    null,
    'X5: the committed docs/adr/DIGEST.md carries no next-free line — regenerate it with ' +
      '`just adr-digest` once the generator derives one',
  );
  assert.equal(
    nextFreeIdFrom(line),
    expectedId,
    `X5: the committed digest must name ${expectedId}, independently recomputed from ` +
      'the file names in docs/adr/',
  );
});

// ===========================================================================
// X6 — README hand-maintains no ADR number, and the clause MOVED rather than
// vanished. Three predicates, each positive-controlled first:
//
//   staleNextFreeParagraphs   — a next-free paragraph carrying a 4-digit run.
//   nextFreeParagraphsNamingDigest — exactly one paragraph must both mention
//                               next-free and name DIGEST.md.
//   loudDigitsOutsideCitations — phrase-independent: any 4-digit run >= 0100
//                               that is not a citation.
//
// Paragraph scope is mandatory in BOTH directions: line scope would false-RED
// the intended replacement (README's resolution rule shares a hard-wrapped line
// with the clause) and false-GREEN the wrapped/tabulated shapes below.
//
// KILLS four measured cheats: (a) leaving README untouched (today's state);
// (b) rewording so the digit survives without the phrase ("Start your new ADR
// at **`0236`**") — caught by the digit census; (c) renaming the phrase
// ("Next available number") — caught by the same census; (d) DELETING the
// clause entirely, which zeroes the stale count vacuously and orphans
// docs/adr/0060-evolution-fusion-content-shape.md:22 ("see docs/adr/README.md
// for the current next-free number") — caught by the moved-not-deleted leg.
// ===========================================================================
test('X6 README states no hand-maintained next-free number and still names DIGEST.md', () => {
  const controls = [
    {
      label: 'stale (i): digit on the same line as the phrase',
      text: [
        'Resolving a reference: an ADR numbered in the harness range goes to the spec corpus.',
        'Next free number: **`0184`**.',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'stale (ii): digit hard-wrapped onto the next line of the paragraph',
      text: [
        'Resolving a reference: the next free number for this directory is currently',
        '**`0184`**, so use that for your new ADR.',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'stale (iii): digit in a table row directly below the phrase',
      text: [
        'The next-free number is tracked in the table below:',
        '| Field | Value |',
        '|-------|-------|',
        '| next free | `0184` |',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'stale (iv): the PHRASE itself hard-wrapped across two lines',
      text: [
        'The catalog is generated, so the only hand-kept value left here is the next',
        'free number, currently **`0184`** for this directory.',
      ].join('\n'),
      stale: 1,
      namesDigest: 0,
      loudDigits: ['0184'],
    },
    {
      label: 'cheat (v): reworded so the digit survives without the phrase',
      text: 'Start your new implementation ADR at **`0236`** (see [`DIGEST.md`](./DIGEST.md)).',
      stale: 0,
      namesDigest: 0,
      loudDigits: ['0236'],
    },
    {
      label: 'cheat (vi): the phrase renamed to "next available"',
      text: 'Next available number: **`0236`** — see [`DIGEST.md`](./DIGEST.md) for the catalog.',
      stale: 0,
      namesDigest: 0,
      loudDigits: ['0236'],
    },
    {
      label: 'clean: the replacement text the specialist is aiming at',
      text: [
        'The next free number is not written here. It is derived at generation time and',
        'rendered into [`DIGEST.md`](./DIGEST.md) by `just adr-digest`; when a number is',
        'reserved for an in-flight slice, the supervisor `mr-state.json` `.adr_next_free`',
        'field is ahead of that line and is authoritative.',
      ].join('\n'),
      stale: 0,
      namesDigest: 1,
      loudDigits: [],
    },
    {
      label: 'clean: ordinary citations must never be reported',
      text: [
        'See ADR-0104 and [0104](./0104-m-infra-d-adr-digest.md) for the generator, or',
        'read `docs/adr/0104-m-infra-d-adr-digest.md` directly.',
      ].join('\n'),
      stale: 0,
      namesDigest: 0,
      loudDigits: [],
    },
    {
      label: 'clean: a bare year is not an ADR-number claim',
      text: 'This catalog was last restructured in 2026 by slice rb-43.',
      stale: 0,
      namesDigest: 0,
      loudDigits: [],
    },
    {
      label: 'mixed: the year is excluded, the bold-code ADR number beside it is not',
      text: 'Last restructured in 2026 by slice rb-43; start your new ADR at **`0236`**.',
      stale: 0,
      namesDigest: 0,
      loudDigits: ['0236'],
    },
  ];

  const controlObserved = controls.map((control) => ({
    label: control.label,
    stale: staleNextFreeParagraphs(control.text).length,
    namesDigest: nextFreeParagraphsNamingDigest(control.text).length,
    loudDigits: loudDigitsOutsideCitations(control.text),
  }));
  const controlExpected = controls.map((control) => ({
    label: control.label,
    stale: control.stale,
    namesDigest: control.namesDigest,
    loudDigits: control.loudDigits,
  }));
  assert.deepEqual(
    controlObserved,
    controlExpected,
    'X6: the three local predicates must report every stale shape and no clean one — if this ' +
      'fails, the matcher is broken and the live verdict below means nothing',
  );

  // --- The real file.
  const readme = readFileSync(join(REAL_ADR_DIR, 'README.md'), 'utf8');
  const stale = staleNextFreeParagraphs(readme);
  const loud = loudDigitsOutsideCitations(readme);
  assert.deepEqual(
    {
      staleParagraphs: stale.length,
      paragraphsNamingDigest: nextFreeParagraphsNamingDigest(readme).length,
      loudDigits: loud,
      mentionsDigestFile: readme.includes('DIGEST.md'),
    },
    {
      staleParagraphs: 0,
      paragraphsNamingDigest: 1,
      loudDigits: [],
      mentionsDigestFile: true,
    },
    'X6: docs/adr/README.md must hand-maintain no ADR number, and exactly ONE paragraph must ' +
      'both mention the next-free number and name DIGEST.md — deleting the clause is not a ' +
      `fix. Un-cited four-digit numbers found (years excluded): ${loud.join(', ') || '(none)'}. ` +
      `Offending paragraph(s):\n${stale.join('\n---\n') || '(none)'}`,
  );
});

// ===========================================================================
// rb-70 SHARED APPARATUS — used by X7 (synthetic corpora) and X8 (real corpus).
// ===========================================================================

/** The prefix scripts/adr-digest.mjs' emitter puts on every error-level issue. */
const RB70_ERROR_PREFIX = 'adr-digest ERROR: ';

/** The prefix it puts on every warn-level issue. Nothing rb-70 emits may wear it. */
const RB70_WARN_PREFIX = 'adr-digest WARN: ';

/**
 * The keyed suffix of the reverse-reciprocity message for the one synthetic gap
 * every clause below re-uses. The arrow is `<=`, NOT `<-`: a sibling text
 * scanner over scripts/adr-digest.mjs asserts set-EQUALITY over the quoted
 * `NNNN->NNNN` / `NNNN<-NNNN` literals in that file, so the Extends gate must
 * not mint keys in that shape. Asserting the arrow here is what stops an
 * implementer from copying the Amends message wholesale.
 */
const RB70_GAP_KEY = '(0952<=0953)';

/** The reverse-gap line, verbatim, prefix included. Template frozen by the slice brief. */
const RB70_EXPECTED_GAP_LINE =
  `${RB70_ERROR_PREFIX}0952: **Extended-by:** ADR-0953 but ADR-0953 has no reciprocal ` +
  '**Extends:** ADR-0952 declaration (0952<=0953)';

/** The two dangling-reference lines, verbatim — same template checkRefs already uses. */
const RB70_EXPECTED_DANGLING_EXTENDS = `${RB70_ERROR_PREFIX}0952: dangling Extends reference "ADR-9999" (ADR-9999 not found)`;
const RB70_EXPECTED_DANGLING_EXTENDED_BY = `${RB70_ERROR_PREFIX}0953: dangling Extended-by reference "ADR-9998" (ADR-9998 not found)`;

/**
 * Run the generator over a throwaway corpus, in generate or --check mode, with
 * BOTH --adr-dir and --out pointed into mkdtemp dirs (see the SAFETY note).
 * The --out target is deliberately NOT pre-created: in check mode a run that
 * reaches the compare exits 1 on "DIGEST.md not found", which is why every
 * clause asserts on a stderr SUBSTRING and never on the exit code alone.
 */
function rb70Probe(entries, options = {}) {
  return withCorpus(entries, (dir) => {
    const outDir = mkdtempSync(join(tmpdir(), 'adr-digest-rb70-'));
    try {
      const base = ['--adr-dir', dir, '--out', join(outDir, 'DIGEST.md')];
      return runDigest(options.check === true ? ['--check', ...base] : base);
    } finally {
      rmSync(outDir, { recursive: true, force: true });
    }
  });
}

function rb70ErrorLines(stderr) {
  return stderr.split('\n').filter((line) => line.startsWith(RB70_ERROR_PREFIX));
}

/** EVERY stderr line carrying the gap key, whatever prefix it wears — so a */
/** warn-level downgrade is visible as "the key is there but the prefix is wrong". */
function rb70KeyLines(stderr) {
  return stderr.split('\n').filter((line) => line.includes(RB70_GAP_KEY));
}

function rb70WarnLinesMentioning(stderr, needle) {
  return stderr
    .split('\n')
    .filter((line) => line.startsWith(RB70_WARN_PREFIX) && line.includes(needle));
}

/** Collapse one probe into the shape every reverse-gap clause compares. */
function rb70GapVerdict(run) {
  const keyLines = rb70KeyLines(run.stderr);
  return {
    exitNonZero: run.code !== 0,
    keyLineCount: keyLines.length,
    errorPrefixed: keyLines.length === 1 && keyLines[0].startsWith(RB70_ERROR_PREFIX),
    saysReciprocal: keyLines.length === 1 && keyLines[0].includes('reciprocal'),
  };
}

const RB70_GAP_EXPECTED = {
  exitNonZero: true,
  keyLineCount: 1,
  errorPrefixed: true,
  saysReciprocal: true,
};

const RB70_SILENT_EXPECTED = {
  exitNonZero: false,
  keyLineCount: 0,
  errorPrefixed: false,
  saysReciprocal: false,
};

/**
 * The canonical reverse-gap corpus: 0952 declares 0953 as an extender, 0953
 * declares nothing. Rebuilt per call so no clause can mutate another's fixture.
 */
function rb70GapEntries() {
  return [adr('0952', { extendedBy: 'ADR-0953' }), adr('0953')];
}

// ===========================================================================
// X7 — **Extends:** / **Extended-by:**, on synthetic corpora only.
//
// Six clause groups; each prints its `RB70-Gn:OK` marker on stdout ONLY after
// its own assertion has passed (assert throws first, so the marker cannot lie).
//
// KILLS, group by group:
//   G1 — the fields are unparsed (today's state), and the mirror cheat of
//        making them REQUIRED (which would red 193 real ADRs).
//   G2 — an always-red implementation (the guard arm), a warn-level downgrade
//        (the ERROR-prefix leg), a `<-` arrow copied from the Amends message,
//        a tolerance/era set (there is none to add), and an em-dash sentinel
//        resolved as if it named an ADR.
//   G3 — `if ((extendsOf.get(x)?.length ?? 0) > 0) continue;`, i.e. testing
//        EMPTINESS instead of MEMBERSHIP. The highest-value mutant in the set:
//        two real ADRs (0208, 0227) each name TWO extenders, so on the live
//        corpus that mutant is invisible. Arm 2 additionally proves a
//        comma-separated multi-id **Extends:** resolves.
//   G4 — reading relations with the RAW bold-field reader instead of the
//        fence-stripped, preamble-bounded back-link view. That mutant survives
//        every other group here; only the fenced / indented / below-the-heading
//        arms see it. Arm 4 is the positive control that stops "always red"
//        from passing G4.
//   G6 — `if (!checkMode) return issues;` and its mirror (mode independence),
//        and `if (adrs.length > 100) return issues;` and every other
//        corpus-size time bomb (scale independence).
//
// NOT TESTED ON PURPOSE: forward reciprocity (**Extends:** ⇒ **Extended-by:**).
// rb-70 DEFERred it as wontfix and the live corpus has ~44 one-directional
// edges. Every fixture below that declares an **Extends:** edge also gives the
// target its reciprocal **Extended-by:**, so these arms stay silent whether or
// not a future slice adds the forward rule — they neither demand it nor forbid it.
// ===========================================================================
test('X7 Extends/Extended-by dangling refs error and every reverse back-link is reciprocal', () => {
  // ---- G1: dangling references, both fields, both modes, plus the two
  // false-positive arms that keep the fields OPTIONAL. --------------------
  const danglingEntries = () => [
    adr('0952', { extends: 'ADR-9999' }),
    adr('0953', { extendedBy: 'ADR-9998' }),
  ];
  const g1Cases = [
    { label: 'dangling, generate', entries: danglingEntries(), check: false, dangling: true },
    { label: 'dangling, --check', entries: danglingEntries(), check: true, dangling: true },
    {
      label: 'every target present, generate',
      entries: [adr('0952', { extends: 'ADR-0953' }), adr('0953', { extendedBy: 'ADR-0952' })],
      check: false,
      dangling: false,
    },
    // NOTE: there is deliberately no clean-corpus --check arm here. A --check
    // run that finds no validation error walks on to the DIGEST compare and
    // exits 1 on "DIGEST.md not found" at the (intentionally uncreated) --out
    // path, so its exit code says nothing about Extends at all. Check-mode
    // no-false-positive behaviour is proved where the exit code IS meaningful:
    // G6 asserts the gap LINE, not the code.
    {
      // The optionality arm. A `**Extends:** is required (use — if none)` reading
      // of the contract reds here — and would red all 193 real ADRs that declare
      // neither field.
      label: 'neither field declared at all, generate',
      entries: [adr('0952'), adr('0953')],
      check: false,
      dangling: false,
    },
  ];

  const g1Observed = g1Cases.map((testCase) => {
    const run = rb70Probe(testCase.entries, { check: testCase.check });
    return {
      label: testCase.label,
      exitNonZero: run.code !== 0,
      namesExtendsDangling: run.stderr.includes(RB70_EXPECTED_DANGLING_EXTENDS),
      namesExtendedByDangling: run.stderr.includes(RB70_EXPECTED_DANGLING_EXTENDED_BY),
      errorCount: rb70ErrorLines(run.stderr).length,
    };
  });
  const g1Expected = g1Cases.map((testCase) => ({
    label: testCase.label,
    exitNonZero: testCase.dangling,
    namesExtendsDangling: testCase.dangling,
    namesExtendedByDangling: testCase.dangling,
    errorCount: testCase.dangling ? 2 : 0,
  }));
  assert.deepEqual(
    g1Observed,
    g1Expected,
    'X7/G1: **Extends:** and **Extended-by:** must join the dangling-reference checks — a ' +
      'missing target is an ERROR naming the FIELD and the ID, in generate AND --check mode — ' +
      'while BOTH fields stay OPTIONAL: a corpus that declares neither must exit 0. The ' +
      'expected lines are verbatim:\n' +
      `  ${RB70_EXPECTED_DANGLING_EXTENDS}\n  ${RB70_EXPECTED_DANGLING_EXTENDED_BY}`,
  );
  console.log('RB70-G1:OK');

  // ---- G2: the reverse gap itself, its exact wording, and the guard arm
  // that an always-red implementation cannot survive. ---------------------
  const g2GapRun = rb70Probe(rb70GapEntries());
  const g2KeyLines = rb70KeyLines(g2GapRun.stderr);

  // Guard arm. 0953 now declares the reciprocal **Extends:**; two further ADRs
  // carry em-dash sentinels, which must satisfy nothing, produce no gap of
  // their own, and not crash the resolver. 0955's parenthetical NAMES 0953 so
  // that a resolver which reaches for the prefix-only id scanner (instead of
  // truncating the token at its first `(`) invents a 0955<=0953 gap and reds.
  const g2GuardRun = rb70Probe([
    adr('0952', { extendedBy: 'ADR-0953' }),
    adr('0953', { extends: 'ADR-0952' }),
    adr('0954', { extendedBy: '—' }),
    adr('0955', { extendedBy: '— (ADR-0953 pending)' }),
  ]);

  assert.deepEqual(
    {
      gap: {
        ...rb70GapVerdict(g2GapRun),
        exactLine: g2KeyLines.length === 1 ? g2KeyLines[0] : g2KeyLines.join(' | '),
        warnLinesAboutExtends: rb70WarnLinesMentioning(g2GapRun.stderr, 'Extends').length,
      },
      guard: {
        exitCode: g2GuardRun.code,
        errorCount: rb70ErrorLines(g2GuardRun.stderr).length,
        mentions0952: g2GuardRun.stderr.includes('0952'),
        mentions0953: g2GuardRun.stderr.includes('0953'),
        warnLinesAboutExtends: rb70WarnLinesMentioning(g2GuardRun.stderr, 'Extends').length,
      },
    },
    {
      gap: {
        ...RB70_GAP_EXPECTED,
        exactLine: RB70_EXPECTED_GAP_LINE,
        warnLinesAboutExtends: 0,
      },
      guard: {
        exitCode: 0,
        errorCount: 0,
        mentions0952: false,
        mentions0953: false,
        warnLinesAboutExtends: 0,
      },
    },
    'X7/G2: an **Extended-by:** with no reciprocal **Extends:** must produce EXACTLY this ' +
      `ERROR line:\n  ${RB70_EXPECTED_GAP_LINE}\n` +
      '(note the `<=` arrow, not `<-`: the sibling corpus eval asserts set-EQUALITY over the ' +
      '`->`/`<-` keyed literals in scripts/adr-digest.mjs). It must be an ERROR, not a WARN, ' +
      'and no tolerance/era WARN line may be added. The guard arm must be COMPLETELY silent — ' +
      'reciprocal pair plus two em-dash sentinels — so "always red" cannot pass this clause.',
  );
  console.log('RB70-G2:OK');

  // ---- G3: MEMBERSHIP, not emptiness. -----------------------------------
  // 0952 names 0953 as its extender. 0953 declares **Extends:** — but at 0954,
  // NOT at 0952. An implementation that skips X as soon as its Extends set is
  // non-empty reports nothing and goes green on the live corpus too, because
  // 0208 and 0227 each name two extenders. 0954 carries the reciprocal
  // **Extended-by:** in both arms, so no forward edge is left dangling and the
  // arms do not depend on forward reciprocity being absent.
  const g3Arms = [
    {
      label: 'extends a DIFFERENT ADR — the gap stands',
      entries: [
        adr('0952', { extendedBy: 'ADR-0953' }),
        adr('0953', { extends: 'ADR-0954' }),
        adr('0954', { extendedBy: 'ADR-0953' }),
      ],
      expected: RB70_GAP_EXPECTED,
    },
    {
      label: 'multi-id list containing 0952 — silent',
      entries: [
        adr('0952', { extendedBy: 'ADR-0953' }),
        adr('0953', { extends: 'ADR-0954, ADR-0952' }),
        adr('0954', { extendedBy: 'ADR-0953' }),
      ],
      expected: RB70_SILENT_EXPECTED,
    },
  ];
  assert.deepEqual(
    g3Arms.map((arm) => ({ label: arm.label, ...rb70GapVerdict(rb70Probe(arm.entries)) })),
    g3Arms.map((arm) => ({ label: arm.label, ...arm.expected })),
    "X7/G3: reciprocity is MEMBERSHIP of the specific id in the extender's **Extends:** set, " +
      'not "the extender declares SOMETHING". Arm 1 keeps a non-empty but wrong Extends set and ' +
      'the gap must still be reported; arm 2 puts the right id in a comma-separated list and the ' +
      'run must be silent (multi-id lists must resolve, as ADR-0238 already ships one).',
  );
  console.log('RB70-G3:OK');

  // ---- G4: which spellings COUNT as a declaration. ----------------------
  // Only a column-0 marker in the fence-free header preamble does. The three
  // negative arms are the sole tooth on "read the relation with the raw
  // bold-field reader" — that mutant passes G1, G2, G3 and G6 unchanged.
  const g4Arms = [
    {
      label: 'fenced inside the preamble',
      extenderOptions: {
        extraPreamble: ['', '```text', '**Extends:** ADR-0952', '```'],
      },
      expected: RB70_GAP_EXPECTED,
    },
    {
      label: 'indented four spaces (a markdown code block)',
      extenderOptions: { extraPreamble: ['    **Extends:** ADR-0952'] },
      expected: RB70_GAP_EXPECTED,
    },
    {
      label: 'below the first `## ` heading (body prose, not a header field)',
      extenderOptions: { extraBody: ['**Extends:** ADR-0952', ''] },
      expected: RB70_GAP_EXPECTED,
    },
    {
      label: 'plain column-0 declaration in the preamble — this one IS a declaration',
      extenderOptions: { extends: 'ADR-0952' },
      expected: RB70_SILENT_EXPECTED,
    },
  ];
  assert.deepEqual(
    g4Arms.map((arm) => ({
      label: arm.label,
      ...rb70GapVerdict(
        rb70Probe([adr('0952', { extendedBy: 'ADR-0953' }), adr('0953', arm.extenderOptions)]),
      ),
    })),
    g4Arms.map((arm) => ({ label: arm.label, ...arm.expected })),
    'X7/G4: relations must be read off the FENCE-STRIPPED, PREAMBLE-BOUNDED back-link view ' +
      'with the marker at column 0 — an illustrative **Extends:** inside a fence, an indented ' +
      'copy (markdown renders it as a code block) and a line of body prose below the first ' +
      '`## ` heading are NOT declarations and must leave the gap standing, while a plain ' +
      'column-0 header line must silence it. Reading the field with the raw bold-field reader ' +
      'passes every other clause in this test and fails only here.',
  );
  console.log('RB70-G4:OK');

  // ---- G6: mode independence AND scale independence. --------------------
  const g6CheckRun = rb70Probe(rb70GapEntries(), { check: true });

  const g6Padded = rb70GapEntries();
  for (let n = 0; n < 120; n++) {
    g6Padded.push(adr(String(100 + n).padStart(4, '0'), { subsystems: 'tooling-docs' }));
  }
  const g6ScaleRun = rb70Probe(g6Padded);

  assert.deepEqual(
    {
      checkMode: rb70GapVerdict(g6CheckRun),
      scale: rb70GapVerdict(g6ScaleRun),
      // Guards the scale arm against silently shrinking into a small corpus.
      corpusSize: g6Padded.length,
    },
    {
      checkMode: RB70_GAP_EXPECTED,
      scale: RB70_GAP_EXPECTED,
      corpusSize: 122,
    },
    'X7/G6: the reverse-reciprocity check must be MODE-independent (`just ci` only ever runs ' +
      '--check, so a check-mode-only or generate-mode-only guard is half dead) and ' +
      'SIZE-independent (no `if (adrs.length > N) return issues;` escape hatch, no era window, ' +
      'no tolerance set). The check-mode probe asserts the gap LINE, never the exit code alone: ' +
      'a run that reaches the compare exits 1 anyway on a missing DIGEST.md.',
  );
  console.log('RB70-G6:OK');
});

// ===========================================================================
// X8 — the FROZEN real-corpus **Extends:** roster.
//
// This is the sole tooth on the second measured bypass: DELETING an
// `**Extended-by:**` line from a real ADR reds nothing. X7's reverse rule
// structurally cannot see it — deleting the line deletes the rule's premise.
//
// Read-only: no spawn, no temp dir, no import of the generator (see the header
// note). The predicates below are a deliberate LOCAL re-implementation.
//
// KILLS, requirement by requirement:
//   - whole-file `includes()`: live body-prose decoys exist. The header line of
//     an edge can be deleted while a backticked or indented mention of the same
//     marker survives further down the SAME file. Hence: preamble only, column
//     0, case-exact.
//   - `content.includes('**Extended-by:**')` (marker presence): 0208 names TWO
//     extenders and 0227 names TWO. Dropping ONE id from either list leaves the
//     marker in place. Hence: parse the id list and assert MEMBERSHIP.
//     0227's value carries commas INSIDE parentheticals, so the split is
//     top-level-only.
//   - a roster DERIVED by walking the corpus's own **Extends:** lines: deleting
//     the declaration deletes the pair, and the tooth passes vacuously. Hence:
//     a hard-coded constant with a pinned length.
//   - "go green by deleting the **Extends:** side instead": hence BOTH legs.
//
// BOUND — the roster is a SUBSET of the live edge set, never its equal. A
// future ADR that adds a new **Extends:** edge must NOT red this test; only a
// change to one of these six edges may.
// ===========================================================================

const RB70_EXTENDS_MARKER = '**Extends:**';
const RB70_EXTENDED_BY_MARKER = '**Extended-by:**';

/** The header preamble: everything above the first `## ` section heading. */
function rb70Preamble(content) {
  const boundary = content.indexOf('\n## ');
  return boundary === -1 ? content : content.slice(0, boundary);
}

/**
 * Split a relation value on TOP-LEVEL commas only. ADR-0227's **Extended-by:**
 * value is `ADR-0236 (rb-46 — ..., residual ... closed), ADR-0237 (...)`: a
 * naive split on every comma shreds the parentheticals into fragments that
 * have no `(` left to truncate at, and those fragments then resolve stray
 * four-digit runs out of the prose.
 */
function rb70SplitTopLevelCommas(value) {
  const tokens = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < value.length; i++) {
    const ch = value[i];
    if (ch === '(') depth++;
    else if (ch === ')') depth = depth > 0 ? depth - 1 : 0;
    else if (ch === ',' && depth === 0) {
      tokens.push(value.slice(start, i));
      start = i + 1;
    }
  }
  tokens.push(value.slice(start));
  return tokens;
}

/**
 * The set of ADR ids declared by `marker` in the HEADER of `content`: preamble
 * only, marker at column 0, case-exact. Every matching line contributes (an
 * ADR may repeat the marker); each token is truncated at its first `(`, may
 * carry an `ADR-` prefix or be bare, and must be exactly four digits.
 */
function rb70DeclaredIds(content, marker) {
  const ids = new Set();
  for (const line of rb70Preamble(content).split('\n')) {
    if (!line.startsWith(marker)) continue;
    for (const rawToken of rb70SplitTopLevelCommas(line.slice(marker.length))) {
      const paren = rawToken.indexOf('(');
      let token = (paren === -1 ? rawToken : rawToken.slice(0, paren)).trim();
      if (token.startsWith('ADR-')) token = token.slice(4);
      if (token.length < 4) continue;
      let digits = 0;
      while (digits < 4 && token[digits] >= '0' && token[digits] <= '9') digits++;
      if (digits !== 4) continue;
      const next = token[4];
      if (next !== undefined && next >= '0' && next <= '9') continue;
      ids.add(token.slice(0, 4));
    }
  }
  return ids;
}

/** Resolve `NNNN` to its file in docs/adr/ by name prefix; null when absent. */
function rb70RealAdrPath(id) {
  const prefix = `${id}-`;
  for (const file of readdirSync(REAL_ADR_DIR)) {
    if (file.startsWith(prefix) && file.endsWith('.md')) return join(REAL_ADR_DIR, file);
  }
  return null;
}

/**
 * FROZEN. Six real edges, hand-transcribed on 2026-09-07, read as
 * "`extender` declares **Extends:** ADR-`extended`, and `extended` declares
 * **Extended-by:** ADR-`extender`". Not derived from the corpus, ON PURPOSE —
 * see the KILLS note above.
 */
const RB70_EXTENDS_ROSTER = [
  { extender: '0222', extended: '0208' },
  { extender: '0223', extended: '0208' },
  { extender: '0227', extended: '0225' },
  { extender: '0236', extended: '0227' },
  { extender: '0237', extended: '0227' },
  { extender: '0238', extended: '0226' },
];

// Appended to X8's failure message. A source comment is not good enough: the
// person reading the CI log only ever sees the message.
const RB70_ROSTER_REPIN_NOTE =
  'IF THIS FAILED BECAUSE THE CORPUS LEGITIMATELY MOVED — an ADR was renumbered, or an ' +
  '**Extends:** edge was deliberately withdrawn with BOTH headers edited in the same commit — ' +
  'then there is no bug and "a back-link was silently deleted" is the wrong diagnosis. The fix ' +
  'is to RE-PIN: edit RB70_EXTENDS_ROSTER in this file so it again names SIX real edges (swap ' +
  'in a surviving pair for the withdrawn one) and say in the commit message which change moved ' +
  'it. Do NOT derive the roster from the corpus and do NOT delete the length pin: a roster read ' +
  'out of the corpus goes green the instant a declaration is deleted, which is precisely the ' +
  'deletion this test exists to catch. The roster is a SUBSET of the live edge set — a NEW ' +
  '**Extends:** edge added by a later ADR needs no edit here and must never red this test.';

test('X8 six real Extends/Extended-by edges resolve on both legs, frozen by roster', () => {
  assert.equal(
    RB70_EXTENDS_ROSTER.length,
    6,
    'X8: the roster is FROZEN at six edges. Shrinking it is how this tooth stops biting; if an ' +
      `edge legitimately went away, swap in a replacement. ${RB70_ROSTER_REPIN_NOTE}`,
  );

  const observed = RB70_EXTENDS_ROSTER.map(({ extender, extended }) => {
    const extenderPath = rb70RealAdrPath(extender);
    const extendedPath = rb70RealAdrPath(extended);
    const extenderText = extenderPath === null ? '' : readFileSync(extenderPath, 'utf8');
    const extendedText = extendedPath === null ? '' : readFileSync(extendedPath, 'utf8');
    return {
      edge: `${extender}->${extended}`,
      extenderFileFound: extenderPath !== null,
      extendedFileFound: extendedPath !== null,
      // Forward leg: the extender's own header names the ADR it extends.
      forwardLegDeclared: rb70DeclaredIds(extenderText, RB70_EXTENDS_MARKER).has(extended),
      // Reverse leg: the extended ADR's header names it back. THIS is the leg
      // the bypass deletes.
      reverseLegDeclared: rb70DeclaredIds(extendedText, RB70_EXTENDED_BY_MARKER).has(extender),
    };
  });
  const expected = RB70_EXTENDS_ROSTER.map(({ extender, extended }) => ({
    edge: `${extender}->${extended}`,
    extenderFileFound: true,
    extendedFileFound: true,
    forwardLegDeclared: true,
    reverseLegDeclared: true,
  }));

  assert.deepEqual(
    observed,
    expected,
    'X8: each frozen edge must resolve on BOTH legs, from a COLUMN-0, case-exact marker in the ' +
      "file's header preamble (above the first `## ` heading) — body prose does not count, and " +
      'the specific id must be a MEMBER of the parsed list, not merely somewhere on the line. ' +
      `${RB70_ROSTER_REPIN_NOTE}`,
  );
  console.log('RB70-G5:OK');
});
